# Generating the dataset

In [10]:
# This reads the key-value pairs from the .env file and loads them into the current process's environment variables. 
# It returns True if it successfully found and loaded a .env file, or False if it couldn't find one
from dotenv import load_dotenv
load_dotenv()

True

In [ ]:
# define a Pydantic model for a single exercise

# Each field has a type (str here for all of them) — Pydantic will enforce that.
# When you pass this model to the LLM as a schema, these descriptions get sent along too, essentially as mini-instructions 
# telling the model what should go in each field and what format/example to follow (e.g. "Unique identifier, e.g. 'push-up-001'" 
# nudges the model toward a consistent ID scheme).
# Every field is required (no Optional or default), so the model has to fill in all of them for a valid Exercise.

In [1]:
from pydantic import BaseModel, Field
from typing import List

class Exercise(BaseModel):
    id: str = Field(description="Unique identifier, e.g. 'push-up-001'")
    exercise_name: str = Field(description="Name of the exercise")
    type_of_activity: str = Field(description="Strength, Cardio, Flexibility, etc.")
    type_of_equipment: str = Field(description="Dumbbells, Barbell, None (bodyweight), etc.")
    body_part: str = Field(description="Chest, Back, Legs, etc.")
    type: str = Field(description="Compound, Isolation, etc.")
    muscle_groups_activated: str = Field(description="Comma-separated list, e.g. 'Chest, Triceps, Shoulders'")
    instructions: str = Field(description="Detailed step-by-step instructions")

# This represents many exercises at once — a list of Exercise objects under one exercises field. 
# This is the model you'd actually pass to the LLM call when you want it to generate a whole batch in one go, rather than asking 
# for one exercise at a time.

class ExerciseDataset(BaseModel):
    exercises: List[Exercise]

In [9]:
from openai import OpenAI # imports the OpenAI client class from the openai Python package.
openai_client = OpenAI() # creates an instance of that client, which handles authentication and communication with OpenAI's API.

import pandas as pd # import pandas library — the standard Python tool for working with tabular data

# Set instructions to guide the LLM behavior for the excercise data generation
prompt = """
Generate a dataset of 50 diverse fitness exercises.
Cover different muscle groups, equipment types, and difficulty levels.
Include bodyweight exercises, free weights, and machine exercises.
""".strip()

# For structured output we switch to responses.parse and pass text_format=ExerciseDataset, which tells the API 
# to return our class instead of free text.

response = openai_client.responses.parse(
    model="gpt-5.4-mini",
    input=[{"role": "user", "content": prompt}],
    text_format=ExerciseDataset,
)

dataset = response.output_parsed
df = pd.DataFrame([ex.model_dump() for ex in dataset.exercises])
df.to_csv("data/data.csv", index=False)
print(f"Generated {len(df)} exercises")

Generated 50 exercises

In [7]:
import os
print(os.getcwd())

/Users/vincentaina/fitness-assistant-practice/fitness-assistant

In [8]:
import os
os.makedirs("/Users/vincentaina/fitness-assistant-practice/fitness-assistant/data", exist_ok=True)

In [11]:
df

,id,exercise_name,type_of_activity,type_of_equipment,body_part,type,muscle_groups_activated,instructions
0,push-up-001,Push-Up,Strength,None (bodyweight),Chest,Compound,"Chest, Triceps, Shoulders, Core",Start in a plank position with hands slightly ...
1,bodyweight-squat-002,Bodyweight Squat,Strength,None (bodyweight),Legs,Compound,"Quadriceps, Glutes, Hamstrings, Core",Stand with your feet shoulder-width apart and ...
2,plank-003,Plank,Strength,None (bodyweight),Core,Isometric,"Core, Shoulders, Glutes",Place your forearms on the floor with elbows u...
3,lunges-004,Forward Lunge,Strength,None (bodyweight),Legs,Compound,"Quadriceps, Glutes, Hamstrings, Calves, Core",Stand tall with feet hip-width apart. Step for...
4,jumping-jacks-005,Jumping Jacks,Cardio,None (bodyweight),Full Body,Compound,"Calves, Quadriceps, Shoulders, Core",Stand upright with feet together and arms at y...
5,glute-bridge-006,Glute Bridge,Strength,None (bodyweight),Glutes,Compound,"Glutes, Hamstrings, Core",Lie on your back with knees bent and feet flat...
6,pull-up-007,Pull-Up,Strength,Pull-up Bar,Back,Compound,"Lats, Biceps, Rhomboids, Rear Delts, Core",Grip the pull-up bar slightly wider than shoul...
7,bicep-curl-008,Dumbbell Bicep Curl,Strength,Dumbbells,Arms,Isolation,"Biceps, Forearms",Stand tall with a dumbbell in each hand and pa...
8,shoulder-press-009,Dumbbell Shoulder Press,Strength,Dumbbells,Shoulders,Compound,"Deltoids, Triceps, Upper Chest, Core",Sit or stand holding dumbbells at shoulder hei...
9,bench-press-010,Barbell Bench Press,Strength,Barbell,Chest,Compound,"Chest, Triceps, Shoulders",Lie on a flat bench with your feet planted on ...
10,deadlift-011,Conventional Deadlift,Strength,Barbell,Full Body,Compound,"Glutes, Hamstrings, Back, Core, Forearms",Stand with your mid-foot under the barbell and...
11,barbell-squat-012,Barbell Back Squat,Strength,Barbell,Legs,Compound,"Quadriceps, Glutes, Hamstrings, Core, Lower Back",Position the barbell across your upper back an...
12,romanian-deadlift-013,Romanian Deadlift,Strength,Barbell,Hamstrings,Compound,"Hamstrings, Glutes, Lower Back, Core",Stand holding a barbell in front of your thigh...
13,lat-pulldown-014,Lat Pulldown,Strength,Machine,Back,Compound,"Lats, Biceps, Rhomboids, Rear Delts",Sit at the lat pulldown machine and secure you...
14,leg-press-015,Leg Press,Strength,Machine,Legs,Compound,"Quadriceps, Glutes, Hamstrings",Sit on the leg press machine with your feet sh...
15,chest-fly-016,Machine Chest Fly,Strength,Machine,Chest,Isolation,"Chest, Front Delts",Sit on the chest fly machine with your back su...
16,leg-extension-017,Leg Extension,Strength,Machine,Legs,Isolation,Quadriceps,Sit on the leg extension machine and position ...
17,hamstring-curl-018,Seated Hamstring Curl,Strength,Machine,Hamstrings,Isolation,"Hamstrings, Calves",Sit on the hamstring curl machine and place yo...
18,seated-row-019,Seated Cable Row,Strength,Cable Machine,Back,Compound,"Lats, Rhomboids, Traps, Biceps, Rear Delts",Sit at the cable row station with your feet on...
19,dips-020,Parallel Bar Dip,Strength,Parallel Bars,Chest,Compound,"Chest, Triceps, Shoulders, Core",Support your body on parallel bars with arms s...
20,mountain-climber-021,Mountain Climber,Cardio,None (bodyweight),Core,Compound,"Core, Shoulders, Hip Flexors, Legs",Start in a high plank position with hands unde...
21,burpee-022,Burpee,Cardio,None (bodyweight),Full Body,Compound,"Chest, Quadriceps, Glutes, Shoulders, Core, Tr...","Stand tall, then squat down and place your han..."
22,sit-up-023,Sit-Up,Strength,None (bodyweight),Core,Compound,"Rectus Abdominis, Hip Flexors",Lie on your back with knees bent and feet plan...
23,russian-twist-024,Russian Twist,Strength,None (bodyweight),Core,Isolation,"Obliques, Rectus Abdominis, Hip Flexors",Sit on the floor with knees bent and lean back...
24,calf-raise-025,Standing Calf Raise,Strength,None (bodyweight),Calves,Isolation,"Gastrocnemius, Soleus",Stand upright with feet about hip-width apart....
25,lateral-raise-026,Dumbbell Lateral Raise,Strength,Dumbbells,Shoulders,Isolation,"Lateral Deltoids, Upper Traps",Stand with a dumbbell in each hand and a sligh...
26,rear-delt-fly-027,Dumbbell Rear Delt Fly,Strength,Dumbbells,Shoulders,Isolation,"Rear Deltoids, Rhomboids, Traps",Hinge at the hips with a flat back and let the...
27,tricep-pushdown-028,Cable Tricep Pushdown,Strength,Cable Machine,Arms,Isolation,"Triceps, Forearms",Stand facing a cable machine with a rope or st...
28,overhead-tricep-extension-029,Overhead Dumbbell Tricep Extension,Strength,Dumbbells,Arms,Isolation,"Triceps, Shoulders, Core",Hold one dumbbell overhead with both hands or ...
29,farmer-carry-030,Farmer's Carry,Strength,Dumbbells,Full Body,Compound,"Forearms, Traps, Core, Glutes, Shoulders",Stand between two heavy dumbbells and pick the...
30,step-up-031,Step-Up,Strength,Bench or Box,Legs,Compound,"Quadriceps, Glutes, Hamstrings, Calves, Core",Stand facing a sturdy bench or box. Place one ...
31,hip-thrust-032,Barbell Hip Thrust,Strength,Barbell,Glutes,Compound,"Glutes, Hamstrings, Core",Sit on the floor with your upper back against ...
32,incline-bench-press-033,Incline Dumbbell Bench Press,Strength,Dumbbells,Chest,Compound,"Upper Chest, Shoulders, Triceps",Lie on an incline bench holding a dumbbell in ...
33,assisted-pull-up-034,Assisted Pull-Up Machine,Strength,Machine,Back,Compound,"Lats, Biceps, Rhomboids, Rear Delts, Core",Set the assistance weight on the pull-up machi...
34,ab-crunch-machine-035,Ab Crunch Machine,Strength,Machine,Core,Isolation,"Rectus Abdominis, Obliques",Sit on the ab crunch machine and position the ...
35,pec-deck-036,Pec Deck Fly,Strength,Machine,Chest,Isolation,"Chest, Front Delts",Sit with your back against the pad and forearm...
36,hack-squat-037,Hack Squat,Strength,Machine,Legs,Compound,"Quadriceps, Glutes, Hamstrings",Stand on the platform of the hack squat machin...
37,smith-machine-squat-038,Smith Machine Squat,Strength,Smith Machine,Legs,Compound,"Quadriceps, Glutes, Hamstrings, Core",Position yourself under the Smith machine bar ...
38,kettlebell-swing-039,Kettlebell Swing,Strength,Kettlebell,Full Body,Compound,"Glutes, Hamstrings, Core, Shoulders, Back",Stand with feet shoulder-width apart and hold ...
39,goblet-squat-040,Goblet Squat,Strength,Kettlebell or Dumbbell,Legs,Compound,"Quadriceps, Glutes, Core, Upper Back",Hold a kettlebell or dumbbell close to your ch...
40,incline-push-up-041,Incline Push-Up,Strength,Bench or Box,Chest,Compound,"Chest, Triceps, Shoulders, Core",Place your hands on a sturdy elevated surface ...
41,wall-sit-042,Wall Sit,Strength,None (bodyweight),Legs,Isometric,"Quadriceps, Glutes, Calves, Core",Stand with your back against a wall and slide ...
42,superman-043,Superman,Strength,None (bodyweight),Back,Isolation,"Lower Back, Glutes, Hamstrings, Upper Back",Lie face down with your arms extended overhead...
43,bird-dog-044,Bird Dog,Strength,None (bodyweight),Core,Compound,"Core, Lower Back, Glutes, Shoulders",Begin on all fours with hands under shoulders ...
44,pallof-press-045,Pallof Press,Strength,Cable Machine,Core,Isolation,"Obliques, Rectus Abdominis, Glutes, Shoulders",Stand sideways to a cable machine and hold the...
45,face-pull-046,Cable Face Pull,Strength,Cable Machine,Shoulders,Isolation,"Rear Delts, Rhomboids, Traps, Rotator Cuff",Set a rope attachment at upper-chest or face h...
46,sled-push-047,Sled Push,Strength,Sled,Full Body,Compound,"Quadriceps, Glutes, Calves, Core, Shoulders",Place your hands on the sled handles and lean ...
47,battle-ropes-048,Battle Ropes,Cardio,Battle Ropes,Full Body,Compound,"Shoulders, Arms, Core, Upper Back, Legs",Stand with feet shoulder-width apart and hold ...
48,trx-row-049,TRX Row,Strength,Suspension Trainer,Back,Compound,"Lats, Rhomboids, Biceps, Rear Delts, Core",Hold the TRX handles and lean back with arms e...
49,donkey-kick-050,Donkey Kick,Strength,None (bodyweight),Glutes,Isolation,"Glutes, Hamstrings, Core",Start on all fours with hands under shoulders ...

In [11]:
df

,id,exercise_name,type_of_activity,type_of_equipment,body_part,type,muscle_groups_activated,instructions
0,push-up-001,Push-Up,Strength,None (bodyweight),Chest,Compound,"Chest, Triceps, Shoulders, Core",Start in a plank position with hands slightly ...
1,bodyweight-squat-002,Bodyweight Squat,Strength,None (bodyweight),Legs,Compound,"Quadriceps, Glutes, Hamstrings, Core",Stand with your feet shoulder-width apart and ...
2,plank-003,Plank,Strength,None (bodyweight),Core,Isometric,"Core, Shoulders, Glutes",Place your forearms on the floor with elbows u...
3,lunges-004,Forward Lunge,Strength,None (bodyweight),Legs,Compound,"Quadriceps, Glutes, Hamstrings, Calves, Core",Stand tall with feet hip-width apart. Step for...
4,jumping-jacks-005,Jumping Jacks,Cardio,None (bodyweight),Full Body,Compound,"Calves, Quadriceps, Shoulders, Core",Stand upright with feet together and arms at y...
5,glute-bridge-006,Glute Bridge,Strength,None (bodyweight),Glutes,Compound,"Glutes, Hamstrings, Core",Lie on your back with knees bent and feet flat...
6,pull-up-007,Pull-Up,Strength,Pull-up Bar,Back,Compound,"Lats, Biceps, Rhomboids, Rear Delts, Core",Grip the pull-up bar slightly wider than shoul...
7,bicep-curl-008,Dumbbell Bicep Curl,Strength,Dumbbells,Arms,Isolation,"Biceps, Forearms",Stand tall with a dumbbell in each hand and pa...
8,shoulder-press-009,Dumbbell Shoulder Press,Strength,Dumbbells,Shoulders,Compound,"Deltoids, Triceps, Upper Chest, Core",Sit or stand holding dumbbells at shoulder hei...
9,bench-press-010,Barbell Bench Press,Strength,Barbell,Chest,Compound,"Chest, Triceps, Shoulders",Lie on a flat bench with your feet planted on ...
10,deadlift-011,Conventional Deadlift,Strength,Barbell,Full Body,Compound,"Glutes, Hamstrings, Back, Core, Forearms",Stand with your mid-foot under the barbell and...
11,barbell-squat-012,Barbell Back Squat,Strength,Barbell,Legs,Compound,"Quadriceps, Glutes, Hamstrings, Core, Lower Back",Position the barbell across your upper back an...
12,romanian-deadlift-013,Romanian Deadlift,Strength,Barbell,Hamstrings,Compound,"Hamstrings, Glutes, Lower Back, Core",Stand holding a barbell in front of your thigh...
13,lat-pulldown-014,Lat Pulldown,Strength,Machine,Back,Compound,"Lats, Biceps, Rhomboids, Rear Delts",Sit at the lat pulldown machine and secure you...
14,leg-press-015,Leg Press,Strength,Machine,Legs,Compound,"Quadriceps, Glutes, Hamstrings",Sit on the leg press machine with your feet sh...
15,chest-fly-016,Machine Chest Fly,Strength,Machine,Chest,Isolation,"Chest, Front Delts",Sit on the chest fly machine with your back su...
16,leg-extension-017,Leg Extension,Strength,Machine,Legs,Isolation,Quadriceps,Sit on the leg extension machine and position ...
17,hamstring-curl-018,Seated Hamstring Curl,Strength,Machine,Hamstrings,Isolation,"Hamstrings, Calves",Sit on the hamstring curl machine and place yo...
18,seated-row-019,Seated Cable Row,Strength,Cable Machine,Back,Compound,"Lats, Rhomboids, Traps, Biceps, Rear Delts",Sit at the cable row station with your feet on...
19,dips-020,Parallel Bar Dip,Strength,Parallel Bars,Chest,Compound,"Chest, Triceps, Shoulders, Core",Support your body on parallel bars with arms s...
20,mountain-climber-021,Mountain Climber,Cardio,None (bodyweight),Core,Compound,"Core, Shoulders, Hip Flexors, Legs",Start in a high plank position with hands unde...
21,burpee-022,Burpee,Cardio,None (bodyweight),Full Body,Compound,"Chest, Quadriceps, Glutes, Shoulders, Core, Tr...","Stand tall, then squat down and place your han..."
22,sit-up-023,Sit-Up,Strength,None (bodyweight),Core,Compound,"Rectus Abdominis, Hip Flexors",Lie on your back with knees bent and feet plan...
23,russian-twist-024,Russian Twist,Strength,None (bodyweight),Core,Isolation,"Obliques, Rectus Abdominis, Hip Flexors",Sit on the floor with knees bent and lean back...
24,calf-raise-025,Standing Calf Raise,Strength,None (bodyweight),Calves,Isolation,"Gastrocnemius, Soleus",Stand upright with feet about hip-width apart....
25,lateral-raise-026,Dumbbell Lateral Raise,Strength,Dumbbells,Shoulders,Isolation,"Lateral Deltoids, Upper Traps",Stand with a dumbbell in each hand and a sligh...
26,rear-delt-fly-027,Dumbbell Rear Delt Fly,Strength,Dumbbells,Shoulders,Isolation,"Rear Deltoids, Rhomboids, Traps",Hinge at the hips with a flat back and let the...
27,tricep-pushdown-028,Cable Tricep Pushdown,Strength,Cable Machine,Arms,Isolation,"Triceps, Forearms",Stand facing a cable machine with a rope or st...
28,overhead-tricep-extension-029,Overhead Dumbbell Tricep Extension,Strength,Dumbbells,Arms,Isolation,"Triceps, Shoulders, Core",Hold one dumbbell overhead with both hands or ...
29,farmer-carry-030,Farmer's Carry,Strength,Dumbbells,Full Body,Compound,"Forearms, Traps, Core, Glutes, Shoulders",Stand between two heavy dumbbells and pick the...
30,step-up-031,Step-Up,Strength,Bench or Box,Legs,Compound,"Quadriceps, Glutes, Hamstrings, Calves, Core",Stand facing a sturdy bench or box. Place one ...
31,hip-thrust-032,Barbell Hip Thrust,Strength,Barbell,Glutes,Compound,"Glutes, Hamstrings, Core",Sit on the floor with your upper back against ...
32,incline-bench-press-033,Incline Dumbbell Bench Press,Strength,Dumbbells,Chest,Compound,"Upper Chest, Shoulders, Triceps",Lie on an incline bench holding a dumbbell in ...
33,assisted-pull-up-034,Assisted Pull-Up Machine,Strength,Machine,Back,Compound,"Lats, Biceps, Rhomboids, Rear Delts, Core",Set the assistance weight on the pull-up machi...
34,ab-crunch-machine-035,Ab Crunch Machine,Strength,Machine,Core,Isolation,"Rectus Abdominis, Obliques",Sit on the ab crunch machine and position the ...
35,pec-deck-036,Pec Deck Fly,Strength,Machine,Chest,Isolation,"Chest, Front Delts",Sit with your back against the pad and forearm...
36,hack-squat-037,Hack Squat,Strength,Machine,Legs,Compound,"Quadriceps, Glutes, Hamstrings",Stand on the platform of the hack squat machin...
37,smith-machine-squat-038,Smith Machine Squat,Strength,Smith Machine,Legs,Compound,"Quadriceps, Glutes, Hamstrings, Core",Position yourself under the Smith machine bar ...
38,kettlebell-swing-039,Kettlebell Swing,Strength,Kettlebell,Full Body,Compound,"Glutes, Hamstrings, Core, Shoulders, Back",Stand with feet shoulder-width apart and hold ...
39,goblet-squat-040,Goblet Squat,Strength,Kettlebell or Dumbbell,Legs,Compound,"Quadriceps, Glutes, Core, Upper Back",Hold a kettlebell or dumbbell close to your ch...
40,incline-push-up-041,Incline Push-Up,Strength,Bench or Box,Chest,Compound,"Chest, Triceps, Shoulders, Core",Place your hands on a sturdy elevated surface ...
41,wall-sit-042,Wall Sit,Strength,None (bodyweight),Legs,Isometric,"Quadriceps, Glutes, Calves, Core",Stand with your back against a wall and slide ...
42,superman-043,Superman,Strength,None (bodyweight),Back,Isolation,"Lower Back, Glutes, Hamstrings, Upper Back",Lie face down with your arms extended overhead...
43,bird-dog-044,Bird Dog,Strength,None (bodyweight),Core,Compound,"Core, Lower Back, Glutes, Shoulders",Begin on all fours with hands under shoulders ...
44,pallof-press-045,Pallof Press,Strength,Cable Machine,Core,Isolation,"Obliques, Rectus Abdominis, Glutes, Shoulders",Stand sideways to a cable machine and hold the...
45,face-pull-046,Cable Face Pull,Strength,Cable Machine,Shoulders,Isolation,"Rear Delts, Rhomboids, Traps, Rotator Cuff",Set a rope attachment at upper-chest or face h...
46,sled-push-047,Sled Push,Strength,Sled,Full Body,Compound,"Quadriceps, Glutes, Calves, Core, Shoulders",Place your hands on the sled handles and lean ...
47,battle-ropes-048,Battle Ropes,Cardio,Battle Ropes,Full Body,Compound,"Shoulders, Arms, Core, Upper Back, Legs",Stand with feet shoulder-width apart and hold ...
48,trx-row-049,TRX Row,Strength,Suspension Trainer,Back,Compound,"Lats, Rhomboids, Biceps, Rear Delts, Core",Hold the TRX handles and lean back with arms e...
49,donkey-kick-050,Donkey Kick,Strength,None (bodyweight),Glutes,Isolation,"Glutes, Hamstrings, Core",Start on all fours with hands under shoulders ...

# The RAG flow

In [13]:
# RAG Architecture - It comes down to three components.
# The pieces are search, the prompt, and the LLM:

# Load the data and create a search index

In [14]:
df = pd.read_csv("data/data.csv")
documents = df.to_dict(orient="records")

In [15]:
# Text fields are the fields you search through. When you type a query, the search engine looks at these fields and tokenizes them. 
# It splits text into words, lowercases them, removes stop words, and ranks the results by relevance. So question, section, and answer 
# are text fields.

# Keyword fields are for exact matching.

from minsearch import Index

index = Index(
    text_fields=[
        "exercise_name",
        "type_of_activity",
        "type_of_equipment",
        "body_part",
        "type",
        "muscle_groups_activated",
        "instructions",
    ],
    keyword_fields=["id"]
)

index.fit(documents)

# implement Search function

In [ ]:
# We do not want to send all documents to LLM cos would be very expensive and not effective 
# We will index the data so only the most relevant docs are retrieved 
# Searching matters because where you have loads of documents. Sending all of them to the LLM would be expensive and slow. 
# The model would get confused with too much data. Search finds the most relevant documents to send instead.

In [17]:
query = "what exercise is similar to push up?"

In [18]:
def search(query):
    boost = {} # no field is treated as more important than another

    results = index.search(
        query=query,
        filter_dict={},  # no filtering. The search runs across everything in the index
        boost_dict=boost,
        num_results=10 # returns the top 10 matches.
    )

    return results

In [20]:
results = search(query)

In [21]:
results

[{'id': 'push-up-001',
  'exercise_name': 'Push-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'None (bodyweight)',
  'body_part': 'Chest',
  'type': 'Compound',
  'muscle_groups_activated': 'Chest, Triceps, Shoulders, Core',
  'instructions': 'Start in a plank position with hands slightly wider than shoulder-width apart. Keep your body in a straight line from head to heels. Lower your chest toward the floor by bending your elbows. Pause briefly, then push through your palms to return to the starting position. Repeat with controlled form.'},
 {'id': 'pull-up-007',
  'exercise_name': 'Pull-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Pull-up Bar',
  'body_part': 'Back',
  'type': 'Compound',
  'muscle_groups_activated': 'Lats, Biceps, Rhomboids, Rear Delts, Core',
  'instructions': 'Grip the pull-up bar slightly wider than shoulder-width with palms facing away. Hang with your arms fully extended and core engaged. Pull your chest toward the bar by driving your elbows down. Lower yourself under control to a full hang.'},
 {'id': 'incline-push-up-041',
  'exercise_name': 'Incline Push-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Bench or Box',
  'body_part': 'Chest',
  'type': 'Compound',
  'muscle_groups_activated': 'Chest, Triceps, Shoulders, Core',
  'instructions': 'Place your hands on a sturdy elevated surface such as a bench or box. Walk your feet back into a straight-body plank. Lower your chest toward the surface by bending your elbows. Press back up to full arm extension.'},
 {'id': 'sled-push-047',
  'exercise_name': 'Sled Push',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Sled',
  'body_part': 'Full Body',
  'type': 'Compound',
  'muscle_groups_activated': 'Quadriceps, Glutes, Calves, Core, Shoulders',
  'instructions': 'Place your hands on the sled handles and lean slightly forward with a strong brace. Drive through the balls of your feet to push the sled forward. Maintain a steady posture and powerful steps. Rest as needed, then repeat.'},
 {'id': 'step-up-031',
  'exercise_name': 'Step-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Bench or Box',
  'body_part': 'Legs',
  'type': 'Compound',
  'muscle_groups_activated': 'Quadriceps, Glutes, Hamstrings, Calves, Core',
  'instructions': 'Stand facing a sturdy bench or box. Place one foot fully on the surface and press through that heel to step your body up. Bring the other foot to meet it, then step back down under control. Alternate legs for even training.'},
 {'id': 'sit-up-023',
  'exercise_name': 'Sit-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'None (bodyweight)',
  'body_part': 'Core',
  'type': 'Compound',
  'muscle_groups_activated': 'Rectus Abdominis, Hip Flexors',
  'instructions': 'Lie on your back with knees bent and feet planted. Cross your arms over your chest or place hands lightly behind your head. Engage your core and lift your torso toward your thighs. Lower back down with control without yanking your neck.'},
 {'id': 'assisted-pull-up-034',
  'exercise_name': 'Assisted Pull-Up Machine',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Machine',
  'body_part': 'Back',
  'type': 'Compound',
  'muscle_groups_activated': 'Lats, Biceps, Rhomboids, Rear Delts, Core',
  'instructions': 'Set the assistance weight on the pull-up machine and place your knees or feet on the pad. Grip the handles and begin from a full stretch. Pull yourself up until your chin approaches the bar. Lower back down smoothly with assistance helping control the load.'},
 {'id': 'goblet-squat-040',
  'exercise_name': 'Goblet Squat',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Kettlebell or Dumbbell',
  'body_part': 'Legs',
  'type': 'Compound',
  'muscle_groups_activated': 'Quadriceps, Glutes, Core, Upper Back',
  'instructions': 'Hold a kettlebell or dumbbell close to your chest with both hands. Stand with feet shoulder-width apart and brace your core. Sit down into a squat while keeping your elbows inside your knees if possible. Push through your heels to stand back up.'},
 {'id': 'hip-thrust-032',
  'exercise_name': 'Barbell Hip Thrust',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Barbell',
  'body_part': 'Glutes',
  'type': 'Compound',
  'muscle_groups_activated': 'Glutes, Hamstrings, Core',
  'instructions': 'Sit on the floor with your upper back against a bench and a barbell over your hips. Bend your knees and place your feet flat on the floor. Drive through your heels to lift your hips until your torso is parallel to the floor. Squeeze your glutes at the top, then lower with control.'},
 {'id': 'pallof-press-045',
  'exercise_name': 'Pallof Press',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Cable Machine',
  'body_part': 'Core',
  'type': 'Isolation',
  'muscle_groups_activated': 'Obliques, Rectus Abdominis, Glutes, Shoulders',
  'instructions': 'Stand sideways to a cable machine and hold the handle at chest level with both hands. Step away until there is tension on the cable. Press the handle straight out in front of your chest without letting your torso rotate. Bring it back in and repeat.'}]

# User Prompt Template

In [26]:
USER_PROMPT_TEMPLATE = """

You're a fitness instructor. Answer the QUESTION based on the CONTEXT from our exercises database.
Use only the facts from the CONTEXT when answering the QUESTION.

Question:
{query}

Context:
{context}
"""

# Building the context

In [27]:
# The context is a formatted string with all the search results:

def build_context(results):
    lines = []
    for r in results:
        entry = (
            f"exercise_name: {r['exercise_name']}\n"
            f"type_of_activity: {r['type_of_activity']}\n"
            f"type_of_equipment: {r['type_of_equipment']}\n"
            f"body_part: {r['body_part']}\n"
            f"type: {r['type']}\n"
            f"muscle_groups_activated: {r['muscle_groups_activated']}\n"
            f"instructions: {r['instructions']}"
        )
        lines.append(entry)
    context = "\n\n".join(lines)
    return context

# Building the Prompt

In [32]:
def build_prompt(query, results):
    context = build_context(results)
    prompt = USER_PROMPT_TEMPLATE.format(
        query=query,
        context=context
    )
    return prompt.strip()

In [33]:
prompt = build_prompt(query, results)

In [34]:
print(prompt)

You're a fitness instructor. Answer the QUESTION based on the CONTEXT from our exercises database.
Use only the facts from the CONTEXT when answering the QUESTION.

Question:
what exercise is similar to push up?

Context:
exercise_name: Push-Up
type_of_activity: Strength
type_of_equipment: None (bodyweight)
body_part: Chest
type: Compound
muscle_groups_activated: Chest, Triceps, Shoulders, Core
instructions: Start in a plank position with hands slightly wider than shoulder-width apart. Keep your body in a straight line from head to heels. Lower your chest toward the floor by bending your elbows. Pause briefly, then push through your palms to return to the starting position. Repeat with controlled form.

exercise_name: Pull-Up
type_of_activity: Strength
type_of_equipment: Pull-up Bar
body_part: Back
type: Compound
muscle_groups_activated: Lats, Biceps, Rhomboids, Rear Delts, Core
instructions: Grip the pull-up bar slightly wider than shoulder-width with palms facing away. Hang with your arms fully extended and core engaged. Pull your chest toward the bar by driving your elbows down. Lower yourself under control to a full hang.

exercise_name: Incline Push-Up
type_of_activity: Strength
type_of_equipment: Bench or Box
body_part: Chest
type: Compound
muscle_groups_activated: Chest, Triceps, Shoulders, Core
instructions: Place your hands on a sturdy elevated surface such as a bench or box. Walk your feet back into a straight-body plank. Lower your chest toward the surface by bending your elbows. Press back up to full arm extension.

exercise_name: Sled Push
type_of_activity: Strength
type_of_equipment: Sled
body_part: Full Body
type: Compound
muscle_groups_activated: Quadriceps, Glutes, Calves, Core, Shoulders
instructions: Place your hands on the sled handles and lean slightly forward with a strong brace. Drive through the balls of your feet to push the sled forward. Maintain a steady posture and powerful steps. Rest as needed, then repeat.

exercise_name: Step-Up
type_of_activity: Strength
type_of_equipment: Bench or Box
body_part: Legs
type: Compound
muscle_groups_activated: Quadriceps, Glutes, Hamstrings, Calves, Core
instructions: Stand facing a sturdy bench or box. Place one foot fully on the surface and press through that heel to step your body up. Bring the other foot to meet it, then step back down under control. Alternate legs for even training.

exercise_name: Sit-Up
type_of_activity: Strength
type_of_equipment: None (bodyweight)
body_part: Core
type: Compound
muscle_groups_activated: Rectus Abdominis, Hip Flexors
instructions: Lie on your back with knees bent and feet planted. Cross your arms over your chest or place hands lightly behind your head. Engage your core and lift your torso toward your thighs. Lower back down with control without yanking your neck.

exercise_name: Assisted Pull-Up Machine
type_of_activity: Strength
type_of_equipment: Machine
body_part: Back
type: Compound
muscle_groups_activated: Lats, Biceps, Rhomboids, Rear Delts, Core
instructions: Set the assistance weight on the pull-up machine and place your knees or feet on the pad. Grip the handles and begin from a full stretch. Pull yourself up until your chin approaches the bar. Lower back down smoothly with assistance helping control the load.

exercise_name: Goblet Squat
type_of_activity: Strength
type_of_equipment: Kettlebell or Dumbbell
body_part: Legs
type: Compound
muscle_groups_activated: Quadriceps, Glutes, Core, Upper Back
instructions: Hold a kettlebell or dumbbell close to your chest with both hands. Stand with feet shoulder-width apart and brace your core. Sit down into a squat while keeping your elbows inside your knees if possible. Push through your heels to stand back up.

exercise_name: Barbell Hip Thrust
type_of_activity: Strength
type_of_equipment: Barbell
body_part: Glutes
type: Compound
muscle_groups_activated: Glutes, Hamstrings, Core
instructions: Sit on the floor with your upper back against a bench and a barbell over your hips. Bend your knees and place your feet flat on the floor. Drive through your heels to lift your hips until your torso is parallel to the floor. Squeeze your glutes at the top, then lower with control.

exercise_name: Pallof Press
type_of_activity: Strength
type_of_equipment: Cable Machine
body_part: Core
type: Isolation
muscle_groups_activated: Obliques, Rectus Abdominis, Glutes, Shoulders
instructions: Stand sideways to a cable machine and hold the handle at chest level with both hands. Step away until there is tension on the cable. Press the handle straight out in front of your chest without letting your torso rotate. Bring it back in and repeat.

# The LLM function

In [35]:
def llm(prompt, model="gpt-5.4-mini"):
    response = openai_client.responses.create(
        model=model,
        input=[{"role": "user", "content": prompt}]
    )

    return response.output_text

In [36]:
response.output_text # exploring the response

'{"exercises":[{"id":"push-up-001","exercise_name":"Push-Up","type_of_activity":"Strength","type_of_equipment":"None (bodyweight)","body_part":"Chest","type":"Compound","muscle_groups_activated":"Chest, Triceps, Shoulders, Core","instructions":"Start in a plank position with hands slightly wider than shoulder-width apart. Keep your body in a straight line from head to heels. Lower your chest toward the floor by bending your elbows. Pause briefly, then push through your palms to return to the starting position. Repeat with controlled form."},{"id":"bodyweight-squat-002","exercise_name":"Bodyweight Squat","type_of_activity":"Strength","type_of_equipment":"None (bodyweight)","body_part":"Legs","type":"Compound","muscle_groups_activated":"Quadriceps, Glutes, Hamstrings, Core","instructions":"Stand with your feet shoulder-width apart and toes slightly turned out. Brace your core and sit your hips back as if lowering into a chair. Keep your chest up and knees tracking over your toes. Lower until thighs are parallel to the floor or as low as mobility allows. Drive through your heels to stand back up."},{"id":"plank-003","exercise_name":"Plank","type_of_activity":"Strength","type_of_equipment":"None (bodyweight)","body_part":"Core","type":"Isometric","muscle_groups_activated":"Core, Shoulders, Glutes","instructions":"Place your forearms on the floor with elbows under shoulders. Extend your legs back and lift your body into a straight line from head to heels. Engage your core, glutes, and legs to avoid sagging or piking. Hold the position while breathing steadily."},{"id":"lunges-004","exercise_name":"Forward Lunge","type_of_activity":"Strength","type_of_equipment":"None (bodyweight)","body_part":"Legs","type":"Compound","muscle_groups_activated":"Quadriceps, Glutes, Hamstrings, Calves, Core","instructions":"Stand tall with feet hip-width apart. Step forward with one leg and lower your body until both knees are bent around 90 degrees. Keep your front knee over your ankle and your torso upright. Push through the front heel to return to standing, then switch legs."},{"id":"jumping-jacks-005","exercise_name":"Jumping Jacks","type_of_activity":"Cardio","type_of_equipment":"None (bodyweight)","body_part":"Full Body","type":"Compound","muscle_groups_activated":"Calves, Quadriceps, Shoulders, Core","instructions":"Stand upright with feet together and arms at your sides. Jump your feet out while raising your arms overhead. Immediately jump back to the starting position. Continue at a steady pace with light landings."},{"id":"glute-bridge-006","exercise_name":"Glute Bridge","type_of_activity":"Strength","type_of_equipment":"None (bodyweight)","body_part":"Glutes","type":"Compound","muscle_groups_activated":"Glutes, Hamstrings, Core","instructions":"Lie on your back with knees bent and feet flat on the floor about hip-width apart. Keep your arms by your sides. Squeeze your glutes and lift your hips until your body forms a straight line from shoulders to knees. Pause at the top, then lower slowly."},{"id":"pull-up-007","exercise_name":"Pull-Up","type_of_activity":"Strength","type_of_equipment":"Pull-up Bar","body_part":"Back","type":"Compound","muscle_groups_activated":"Lats, Biceps, Rhomboids, Rear Delts, Core","instructions":"Grip the pull-up bar slightly wider than shoulder-width with palms facing away. Hang with your arms fully extended and core engaged. Pull your chest toward the bar by driving your elbows down. Lower yourself under control to a full hang."},{"id":"bicep-curl-008","exercise_name":"Dumbbell Bicep Curl","type_of_activity":"Strength","type_of_equipment":"Dumbbells","body_part":"Arms","type":"Isolation","muscle_groups_activated":"Biceps, Forearms","instructions":"Stand tall with a dumbbell in each hand and palms facing forward. Keep your elbows close to your torso. Curl the weights up by bending your elbows without swinging your body. Lower the dumbbells slowly to the starting position."},{"id":"shoulder-press-009","exercise_name":"Dumbbell Shoulder Press","type_of_activity":"Strength","type_of_equipment":"Dumbbells","body_part":"Shoulders","type":"Compound","muscle_groups_activated":"Deltoids, Triceps, Upper Chest, Core","instructions":"Sit or stand holding dumbbells at shoulder height with palms facing forward. Brace your core and press the weights overhead until your arms are fully extended. Avoid arching your lower back. Lower the dumbbells back to shoulder height with control."},{"id":"bench-press-010","exercise_name":"Barbell Bench Press","type_of_activity":"Strength","type_of_equipment":"Barbell","body_part":"Chest","type":"Compound","muscle_groups_activated":"Chest, Triceps, Shoulders","instructions":"Lie on a flat bench with your feet planted on the floor. Grip the bar slightly wider than shoulder-width and unrack it over your chest. Lower the bar to mid-chest with control. Press it back up until your arms are extended, keeping your wrists stacked over your elbows."},{"id":"deadlift-011","exercise_name":"Conventional Deadlift","type_of_activity":"Strength","type_of_equipment":"Barbell","body_part":"Full Body","type":"Compound","muscle_groups_activated":"Glutes, Hamstrings, Back, Core, Forearms","instructions":"Stand with your mid-foot under the barbell and feet about hip-width apart. Bend at the hips and knees to grip the bar with a flat back. Brace your core and drive through the floor to lift the bar by extending your hips and knees together. Lower the bar back down with control, keeping it close to your body."},{"id":"barbell-squat-012","exercise_name":"Barbell Back Squat","type_of_activity":"Strength","type_of_equipment":"Barbell","body_part":"Legs","type":"Compound","muscle_groups_activated":"Quadriceps, Glutes, Hamstrings, Core, Lower Back","instructions":"Position the barbell across your upper back and stand with feet shoulder-width apart. Brace your core and descend by bending at the hips and knees. Keep your chest up and knees tracking over your toes. Drive through your heels to stand back up."},{"id":"romanian-deadlift-013","exercise_name":"Romanian Deadlift","type_of_activity":"Strength","type_of_equipment":"Barbell","body_part":"Hamstrings","type":"Compound","muscle_groups_activated":"Hamstrings, Glutes, Lower Back, Core","instructions":"Stand holding a barbell in front of your thighs with a slight bend in your knees. Push your hips back while keeping the bar close to your legs. Lower until you feel a strong stretch in your hamstrings and your back stays neutral. Drive your hips forward to return to standing."},{"id":"lat-pulldown-014","exercise_name":"Lat Pulldown","type_of_activity":"Strength","type_of_equipment":"Machine","body_part":"Back","type":"Compound","muscle_groups_activated":"Lats, Biceps, Rhomboids, Rear Delts","instructions":"Sit at the lat pulldown machine and secure your thighs under the pads. Grip the bar wider than shoulder-width. Pull the bar down toward your upper chest by driving your elbows down and back. Slowly return the bar overhead with control without leaning excessively."},{"id":"leg-press-015","exercise_name":"Leg Press","type_of_activity":"Strength","type_of_equipment":"Machine","body_part":"Legs","type":"Compound","muscle_groups_activated":"Quadriceps, Glutes, Hamstrings","instructions":"Sit on the leg press machine with your feet shoulder-width apart on the platform. Unlock the sled and lower it by bending your knees until they reach a comfortable depth. Keep your lower back and hips against the seat. Press through your feet to return to the starting position without locking out aggressively."},{"id":"chest-fly-016","exercise_name":"Machine Chest Fly","type_of_activity":"Strength","type_of_equipment":"Machine","body_part":"Chest","type":"Isolation","muscle_groups_activated":"Chest, Front Delts","instructions":"Sit on the chest fly machine with your back supported and elbows slightly bent. Bring the handles together in front of your chest in a hugging motion. Squeeze your chest at the peak. Return the handles slowly until you feel a stretch across your chest."},{"id":"leg-extension-017","exercise_name":"Leg Extension","type_of_activity":"Strength","type_of_equipment":"Machine","body_part":"Legs","type":"Isolation","muscle_groups_activated":"Quadriceps","instructions":"Sit on the leg extension machine and position the pad over your lower shins. Extend your knees to lift the weight until your legs are nearly straight. Pause briefly at the top. Lower the weight under control until your knees are bent again."},{"id":"hamstring-curl-018","exercise_name":"Seated Hamstring Curl","type_of_activity":"Strength","type_of_equipment":"Machine","body_part":"Hamstrings","type":"Isolation","muscle_groups_activated":"Hamstrings, Calves","instructions":"Sit on the hamstring curl machine and place your lower legs behind the roller pad. Curl your heels backward by bending your knees. Squeeze your hamstrings at the end of the movement. Return slowly to the starting position."},{"id":"seated-row-019","exercise_name":"Seated Cable Row","type_of_activity":"Strength","type_of_equipment":"Cable Machine","body_part":"Back","type":"Compound","muscle_groups_activated":"Lats, Rhomboids, Traps, Biceps, Rear Delts","instructions":"Sit at the cable row station with your feet on the platform and knees slightly bent. Hold the handle with a neutral grip and keep your chest tall. Pull the handle toward your torso by squeezing your shoulder blades together. Extend your arms forward again while maintaining posture."},{"id":"dips-020","exercise_name":"Parallel Bar Dip","type_of_activity":"Strength","type_of_equipment":"Parallel Bars","body_part":"Chest","type":"Compound","muscle_groups_activated":"Chest, Triceps, Shoulders, Core","instructions":"Support your body on parallel bars with arms straight and shoulders down. Lower your body by bending your elbows until your upper arms are roughly parallel to the floor. Lean forward slightly to emphasize the chest or stay more upright for triceps focus. Press back up to the starting position."},{"id":"mountain-climber-021","exercise_name":"Mountain Climber","type_of_activity":"Cardio","type_of_equipment":"None (bodyweight)","body_part":"Core","type":"Compound","muscle_groups_activated":"Core, Shoulders, Hip Flexors, Legs","instructions":"Start in a high plank position with hands under shoulders. Drive one knee toward your chest, then quickly switch legs in a running motion. Keep your hips level and your core tight. Continue alternating at a controlled but quick pace."},{"id":"burpee-022","exercise_name":"Burpee","type_of_activity":"Cardio","type_of_equipment":"None (bodyweight)","body_part":"Full Body","type":"Compound","muscle_groups_activated":"Chest, Quadriceps, Glutes, Shoulders, Core, Triceps","instructions":"Stand tall, then squat down and place your hands on the floor. Jump or step your feet back into a plank. Perform a push-up if desired, then jump your feet back toward your hands. Explosively jump upward and reach overhead."},{"id":"sit-up-023","exercise_name":"Sit-Up","type_of_activity":"Strength","type_of_equipment":"None (bodyweight)","body_part":"Core","type":"Compound","muscle_groups_activated":"Rectus Abdominis, Hip Flexors","instructions":"Lie on your back with knees bent and feet planted. Cross your arms over your chest or place hands lightly behind your head. Engage your core and lift your torso toward your thighs. Lower back down with control without yanking your neck."},{"id":"russian-twist-024","exercise_name":"Russian Twist","type_of_activity":"Strength","type_of_equipment":"None (bodyweight)","body_part":"Core","type":"Isolation","muscle_groups_activated":"Obliques, Rectus Abdominis, Hip Flexors","instructions":"Sit on the floor with knees bent and lean back slightly while keeping your spine long. Lift your feet if desired for added difficulty. Rotate your torso from side to side, bringing your hands or weight beside each hip. Move with control and keep your core engaged."},{"id":"calf-raise-025","exercise_name":"Standing Calf Raise","type_of_activity":"Strength","type_of_equipment":"None (bodyweight)","body_part":"Calves","type":"Isolation","muscle_groups_activated":"Gastrocnemius, Soleus","instructions":"Stand upright with feet about hip-width apart. Rise onto the balls of your feet by lifting your heels as high as possible. Pause at the top, then lower your heels slowly back to the floor. Maintain a steady, controlled tempo throughout."},{"id":"lateral-raise-026","exercise_name":"Dumbbell Lateral Raise","type_of_activity":"Strength","type_of_equipment":"Dumbbells","body_part":"Shoulders","type":"Isolation","muscle_groups_activated":"Lateral Deltoids, Upper Traps","instructions":"Stand with a dumbbell in each hand and a slight bend in your elbows. Raise your arms out to the sides until they reach shoulder height. Keep your shoulders down and avoid swinging. Lower the weights slowly."},{"id":"rear-delt-fly-027","exercise_name":"Dumbbell Rear Delt Fly","type_of_activity":"Strength","type_of_equipment":"Dumbbells","body_part":"Shoulders","type":"Isolation","muscle_groups_activated":"Rear Deltoids, Rhomboids, Traps","instructions":"Hinge at the hips with a flat back and let the dumbbells hang beneath your shoulders. With a slight bend in the elbows, raise the weights out to the sides. Squeeze your shoulder blades together at the top. Lower the dumbbells back down under control."},{"id":"tricep-pushdown-028","exercise_name":"Cable Tricep Pushdown","type_of_activity":"Strength","type_of_equipment":"Cable Machine","body_part":"Arms","type":"Isolation","muscle_groups_activated":"Triceps, Forearms","instructions":"Stand facing a cable machine with a rope or straight bar attachment. Keep your elbows tucked close to your sides. Push the handle down until your arms are fully extended. Return slowly until your forearms are above parallel to the floor."},{"id":"overhead-tricep-extension-029","exercise_name":"Overhead Dumbbell Tricep Extension","type_of_activity":"Strength","type_of_equipment":"Dumbbells","body_part":"Arms","type":"Isolation","muscle_groups_activated":"Triceps, Shoulders, Core","instructions":"Hold one dumbbell overhead with both hands or two dumbbells as appropriate. Keep your elbows pointing forward and close together. Bend your elbows to lower the weight behind your head. Extend your arms to lift the weight back overhead."},{"id":"farmer-carry-030","exercise_name":"Farmer\'s Carry","type_of_activity":"Strength","type_of_equipment":"Dumbbells","body_part":"Full Body","type":"Compound","muscle_groups_activated":"Forearms, Traps, Core, Glutes, Shoulders","instructions":"Stand between two heavy dumbbells and pick them up with a neutral grip. Keep your chest tall, shoulders down, and core braced. Walk forward in a controlled manner without leaning or letting the weights swing. Set the weights down safely after the desired distance."},{"id":"step-up-031","exercise_name":"Step-Up","type_of_activity":"Strength","type_of_equipment":"Bench or Box","body_part":"Legs","type":"Compound","muscle_groups_activated":"Quadriceps, Glutes, Hamstrings, Calves, Core","instructions":"Stand facing a sturdy bench or box. Place one foot fully on the surface and press through that heel to step your body up. Bring the other foot to meet it, then step back down under control. Alternate legs for even training."},{"id":"hip-thrust-032","exercise_name":"Barbell Hip Thrust","type_of_activity":"Strength","type_of_equipment":"Barbell","body_part":"Glutes","type":"Compound","muscle_groups_activated":"Glutes, Hamstrings, Core","instructions":"Sit on the floor with your upper back against a bench and a barbell over your hips. Bend your knees and place your feet flat on the floor. Drive through your heels to lift your hips until your torso is parallel to the floor. Squeeze your glutes at the top, then lower with control."},{"id":"incline-bench-press-033","exercise_name":"Incline Dumbbell Bench Press","type_of_activity":"Strength","type_of_equipment":"Dumbbells","body_part":"Chest","type":"Compound","muscle_groups_activated":"Upper Chest, Shoulders, Triceps","instructions":"Lie on an incline bench holding a dumbbell in each hand at chest level. Press the dumbbells upward until your arms are extended without locking aggressively. Lower them slowly until your elbows are slightly below the bench line. Keep your feet planted and core engaged."},{"id":"assisted-pull-up-034","exercise_name":"Assisted Pull-Up Machine","type_of_activity":"Strength","type_of_equipment":"Machine","body_part":"Back","type":"Compound","muscle_groups_activated":"Lats, Biceps, Rhomboids, Rear Delts, Core","instructions":"Set the assistance weight on the pull-up machine and place your knees or feet on the pad. Grip the handles and begin from a full stretch. Pull yourself up until your chin approaches the bar. Lower back down smoothly with assistance helping control the load."},{"id":"ab-crunch-machine-035","exercise_name":"Ab Crunch Machine","type_of_activity":"Strength","type_of_equipment":"Machine","body_part":"Core","type":"Isolation","muscle_groups_activated":"Rectus Abdominis, Obliques","instructions":"Sit on the ab crunch machine and position the pads comfortably against your upper body. Contract your abs to crunch forward through your torso. Avoid pulling with your arms or neck. Return slowly to the starting position."},{"id":"pec-deck-036","exercise_name":"Pec Deck Fly","type_of_activity":"Strength","type_of_equipment":"Machine","body_part":"Chest","type":"Isolation","muscle_groups_activated":"Chest, Front Delts","instructions":"Sit with your back against the pad and forearms or elbows placed on the machine arms. Bring the handles together in front of your chest by squeezing your pecs. Pause briefly at the end range. Let the arms return slowly to the open position."},{"id":"hack-squat-037","exercise_name":"Hack Squat","type_of_activity":"Strength","type_of_equipment":"Machine","body_part":"Legs","type":"Compound","muscle_groups_activated":"Quadriceps, Glutes, Hamstrings","instructions":"Stand on the platform of the hack squat machine with your shoulders under the pads. Unlock the machine and lower yourself by bending your knees. Keep your back supported and heels planted. Press through your feet to return upward."},{"id":"smith-machine-squat-038","exercise_name":"Smith Machine Squat","type_of_activity":"Strength","type_of_equipment":"Smith Machine","body_part":"Legs","type":"Compound","muscle_groups_activated":"Quadriceps, Glutes, Hamstrings, Core","instructions":"Position yourself under the Smith machine bar with feet placed slightly forward. Unrack the bar and lower into a squat while maintaining a neutral spine. Keep your knees tracking over your toes and chest lifted. Drive back up to standing."},{"id":"kettlebell-swing-039","exercise_name":"Kettlebell Swing","type_of_activity":"Strength","type_of_equipment":"Kettlebell","body_part":"Full Body","type":"Compound","muscle_groups_activated":"Glutes, Hamstrings, Core, Shoulders, Back","instructions":"Stand with feet shoulder-width apart and hold the kettlebell with both hands. Hinge at the hips and swing the kettlebell back between your legs. Explosively extend your hips to swing the bell to chest height. Let it arc back down naturally and repeat."},{"id":"goblet-squat-040","exercise_name":"Goblet Squat","type_of_activity":"Strength","type_of_equipment":"Kettlebell or Dumbbell","body_part":"Legs","type":"Compound","muscle_groups_activated":"Quadriceps, Glutes, Core, Upper Back","instructions":"Hold a kettlebell or dumbbell close to your chest with both hands. Stand with feet shoulder-width apart and brace your core. Sit down into a squat while keeping your elbows inside your knees if possible. Push through your heels to stand back up."},{"id":"incline-push-up-041","exercise_name":"Incline Push-Up","type_of_activity":"Strength","type_of_equipment":"Bench or Box","body_part":"Chest","type":"Compound","muscle_groups_activated":"Chest, Triceps, Sho

# Full RAG

In [37]:
# With search, the prompt, and the LLM ready, we wire them together:

def rag(query, model="gpt-5.4-mini"):
    search_results = search(query)
    prompt = build_prompt(query, results)
    answer = llm(prompt, model=model)
    return answer

# Test it

In [38]:
query = "Is the Last Pulldown considered a strength training activity, and if so, why?"
answer = rag(query)
print(answer)

I can’t confirm that from the context provided, because **“Last Pulldown” is not listed in the exercise database**.

If you meant **Pull-Up** or **Assisted Pull-Up Machine**, then **yes**, those are considered **strength training** activities because their `type_of_activity` is **Strength**.