In [4]:
import pandas as pd # import pandas library — the standard Python tool for working with tabular data

In [5]:
# This reads the key-value pairs from the .env file and loads them into the current process's environment variables. 
# It returns True if it successfully found and loaded a .env file, or False if it couldn't find one
from dotenv import load_dotenv
load_dotenv()

True

In [6]:
from openai import OpenAI # imports the OpenAI client class from the openai Python package.
openai_client = OpenAI() # creates an instance of that client, which handles authentication and communication with OpenAI's API.

# Generating Ground Truth Data

In [7]:
# We need questions with known relevant documents.
# We generate these with an LLM, asking it to create questions for each exercise:

# Loading the documents

In [8]:
df = pd.read_csv('../data/data.csv')
documents = df.to_dict(orient='records')

In [9]:
# We'll generate questions for the fitness dataset. 
# The full Fitness dataset contains documents that cover different muscle groups, equipment types, and difficulty levels.

# prompt template for question generation

In [10]:
prompt_template = """
You are a user of a fitness assistant app. Based on the exercise record below,
generate 5 questions a user might ask that this record would be the best answer to.
The questions should be complete and not too short — imagine a real user typing them
without seeing the record itself.

Exercise record:
exercise_name: {exercise_name}
type_of_activity: {type_of_activity}
type_of_equipment: {type_of_equipment}
body_part: {body_part}
type: {type}
muscle_groups_activated: {muscle_groups_activated}
instructions: {instructions}

Provide the output in parsable JSON, as a list of 5 strings, with no other text:

["question1", "question2", ..., "question5"]
""".strip()

# function to call the LLM for one record

In [11]:
documents[0]

{'id': 'push-up-001',
 'exercise_name': 'Push-Up',
 'type_of_activity': 'Strength',
 'type_of_equipment': 'None (bodyweight)',
 'body_part': 'Chest',
 'type': 'Compound',
 'muscle_groups_activated': 'Chest, Triceps, Shoulders, Core',
 'instructions': 'Start in a plank position with hands slightly wider than shoulder-width apart. Keep your body in a straight line from head to heels. Lower your chest toward the floor by bending your elbows. Pause briefly, then push through your palms to return to the starting position. Repeat with controlled form.'}

In [12]:
prompt = prompt_template.format(**documents[0])

In [13]:
prompt

'You are a user of a fitness assistant app. Based on the exercise record below,\ngenerate 5 questions a user might ask that this record would be the best answer to.\nThe questions should be complete and not too short — imagine a real user typing them\nwithout seeing the record itself.\n\nExercise record:\nexercise_name: Push-Up\ntype_of_activity: Strength\ntype_of_equipment: None (bodyweight)\nbody_part: Chest\ntype: Compound\nmuscle_groups_activated: Chest, Triceps, Shoulders, Core\ninstructions: Start in a plank position with hands slightly wider than shoulder-width apart. Keep your body in a straight line from head to heels. Lower your chest toward the floor by bending your elbows. Pause briefly, then push through your palms to return to the starting position. Repeat with controlled form.\n\nProvide the output in parsable JSON, as a list of 5 strings, with no other text:\n\n["question1", "question2", ..., "question5"]'

In [14]:
def llm(prompt):
    response = openai_client.chat.completions.create(
        model='gpt-4o-mini',
        messages=[{"role": "user", "content": prompt}]
    )
    return response.choices[0].message.content

In [15]:
questions = llm(prompt)

In [16]:
questions

'["What are some effective strength exercises I can do without any equipment?", "How can I perform push-ups correctly to ensure I’m getting the most benefit?", "What muscles are engaged when doing push-ups, and which part of the body do they primarily target?", "Can you provide me with step-by-step instructions for doing push-ups to improve my form?", "Is the push-up a good compound exercise, and what are the benefits of including it in my workout routine?"]'

# Generating Ground Truth for All Documents

In [17]:
import json
from tqdm.auto import tqdm

results = {}

for doc in tqdm(documents):
    doc_id = doc['id']
    if doc_id in results:
        continue  # skip if already processed (lets you safely re-run after a failure)
    
    prompt = prompt_template.format(**doc)
    questions_raw = llm(prompt)
    results[doc_id] = questions_raw

  0%|          | 0/50 [00:00<?, ?it/s]

In [18]:
# --- Parse the raw JSON strings into actual lists ---
parsed_results = {}

for doc_id, questions_raw in results.items():
    try:
        parsed_results[doc_id] = json.loads(questions_raw)
    except json.JSONDecodeError:
        print(f"Failed to parse for {doc_id}: {questions_raw[:200]}")


# --- Flatten into (id, question) pairs ---
final_results = []

for doc_id, questions in parsed_results.items():
    for q in questions:
        final_results.append((doc_id, q))

In [19]:
print(len(final_results))       # should be ~250 (50 exercises × 5 questions)
print(final_results[:3])        # should show clean (id, question) tuples

250
[('push-up-001', 'What are some effective bodyweight exercises I can do to strengthen my chest muscles?'), ('push-up-001', "Can you explain the proper technique for performing a push-up to ensure I don't injure myself?"), ('push-up-001', 'What muscle groups are activated when doing push-ups, and how can they benefit my overall fitness?')]

In [20]:
final_results[0]

('push-up-001',
 'What are some effective bodyweight exercises I can do to strengthen my chest muscles?')

In [21]:
df_ground_truth = pd.DataFrame(final_results, columns=['id', 'question'])
df_ground_truth.to_csv('../data/ground-truth-data.csv', index=False)

In [22]:
!head ../data/ground-truth-data.csv

id,question
push-up-001,What are some effective bodyweight exercises I can do to strengthen my chest muscles?
push-up-001,Can you explain the proper technique for performing a push-up to ensure I don't injure myself?
push-up-001,"What muscle groups are activated when doing push-ups, and how can they benefit my overall fitness?"
push-up-001,"Is there any special equipment needed to perform push-ups, or can they be done anywhere?"
push-up-001,What are the benefits of incorporating compound exercises like push-ups into my strength training routine?
bodyweight-squat-002,What are some effective bodyweight exercises I can do to strengthen my legs without any equipment?
bodyweight-squat-002,Can you give me detailed instructions on how to perform a bodyweight squat correctly?
bodyweight-squat-002,What muscle groups are activated when performing bodyweight squats?
bodyweight-squat-002,"Is the bodyweight squat considered a compound exercise, and if so, why?"

In [23]:
df_ground_truth

                  id                                           question
0        push-up-001  What are some effective bodyweight exercises I...
1        push-up-001  Can you explain the proper technique for perfo...
2        push-up-001  What muscle groups are activated when doing pu...
3        push-up-001  Is there any special equipment needed to perfo...
4        push-up-001  What are the benefits of incorporating compoun...
..               ...                                                ...
245  donkey-kick-050  What is the proper technique for performing a ...
246  donkey-kick-050  Can you tell me about a strength exercise that...
247  donkey-kick-050  What muscle groups are activated when I perfor...
248  donkey-kick-050  How do I make sure I'm doing the Donkey Kick c...
249  donkey-kick-050  Could you provide step-by-step instructions fo...

[250 rows x 2 columns]

In [24]:
df_ground_truth.head() # see top 5

            id                                           question
0  push-up-001  What are some effective bodyweight exercises I...
1  push-up-001  Can you explain the proper technique for perfo...
2  push-up-001  What muscle groups are activated when doing pu...
3  push-up-001  Is there any special equipment needed to perfo...
4  push-up-001  What are the benefits of incorporating compoun...

In [25]:
len(df_ground_truth)

250

In [26]:
ground_truth = df_ground_truth.to_dict(orient='records') #easier to deal with dictionaries

In [27]:
ground_truth [0]

{'id': 'push-up-001',
 'question': 'What are some effective bodyweight exercises I can do to strengthen my chest muscles?'}

In [28]:
q = ground_truth[0]
q

{'id': 'push-up-001',
 'question': 'What are some effective bodyweight exercises I can do to strengthen my chest muscles?'}

In [29]:
doc_id = q['id']
doc_id

'push-up-001'

# Evaluating retrieval quality

In [30]:
from ingest import load_fitness_data, build_index

documents = load_fitness_data()
index = build_index(documents)

In [31]:
import os
print(os.getcwd())

/Users/vincentaina/fitness-assistant-practice/fitness-assistant/notebooks

In [32]:
# Now, to compute Hit Rate and MRR, you need three things:
# A ground-truth dataset — a list of queries, each paired with the id of the document that should be retrieved 
# A search function that returns ranked results for each query
# The metric functions themselves

In [33]:
query = "what exercise is similar to push up?"

In [34]:
boost = {} # no field is treated as more important than another

index.search(
        query=query,
        filter_dict={},  # no filtering. The search runs across everything in the index
        boost_dict=boost,
        num_results=10 # returns the top 10 matches.
    )

[{'id': 'push-up-001',
  'exercise_name': 'Push-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'None (bodyweight)',
  'body_part': 'Chest',
  'type': 'Compound',
  'muscle_groups_activated': 'Chest, Triceps, Shoulders, Core',
  'instructions': 'Start in a plank position with hands slightly wider than shoulder-width apart. Keep your body in a straight line from head to heels. Lower your chest toward the floor by bending your elbows. Pause briefly, then push through your palms to return to the starting position. Repeat with controlled form.'},
 {'id': 'pull-up-007',
  'exercise_name': 'Pull-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Pull-up Bar',
  'body_part': 'Back',
  'type': 'Compound',
  'muscle_groups_activated': 'Lats, Biceps, Rhomboids, Rear Delts, Core',
  'instructions': 'Grip the pull-up bar slightly wider than shoulder-width with palms facing away. Hang with your arms fully extended and core engaged. Pull your chest toward the bar by driving your elbows down. Lower yourself under control to a full hang.'},
 {'id': 'incline-push-up-041',
  'exercise_name': 'Incline Push-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Bench or Box',
  'body_part': 'Chest',
  'type': 'Compound',
  'muscle_groups_activated': 'Chest, Triceps, Shoulders, Core',
  'instructions': 'Place your hands on a sturdy elevated surface such as a bench or box. Walk your feet back into a straight-body plank. Lower your chest toward the surface by bending your elbows. Press back up to full arm extension.'},
 {'id': 'sled-push-047',
  'exercise_name': 'Sled Push',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Sled',
  'body_part': 'Full Body',
  'type': 'Compound',
  'muscle_groups_activated': 'Quadriceps, Glutes, Calves, Core, Shoulders',
  'instructions': 'Place your hands on the sled handles and lean slightly forward with a strong brace. Drive through the balls of your feet to push the sled forward. Maintain a steady posture and powerful steps. Rest as needed, then repeat.'},
 {'id': 'step-up-031',
  'exercise_name': 'Step-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Bench or Box',
  'body_part': 'Legs',
  'type': 'Compound',
  'muscle_groups_activated': 'Quadriceps, Glutes, Hamstrings, Calves, Core',
  'instructions': 'Stand facing a sturdy bench or box. Place one foot fully on the surface and press through that heel to step your body up. Bring the other foot to meet it, then step back down under control. Alternate legs for even training.'},
 {'id': 'sit-up-023',
  'exercise_name': 'Sit-Up',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'None (bodyweight)',
  'body_part': 'Core',
  'type': 'Compound',
  'muscle_groups_activated': 'Rectus Abdominis, Hip Flexors',
  'instructions': 'Lie on your back with knees bent and feet planted. Cross your arms over your chest or place hands lightly behind your head. Engage your core and lift your torso toward your thighs. Lower back down with control without yanking your neck.'},
 {'id': 'assisted-pull-up-034',
  'exercise_name': 'Assisted Pull-Up Machine',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Machine',
  'body_part': 'Back',
  'type': 'Compound',
  'muscle_groups_activated': 'Lats, Biceps, Rhomboids, Rear Delts, Core',
  'instructions': 'Set the assistance weight on the pull-up machine and place your knees or feet on the pad. Grip the handles and begin from a full stretch. Pull yourself up until your chin approaches the bar. Lower back down smoothly with assistance helping control the load.'},
 {'id': 'goblet-squat-040',
  'exercise_name': 'Goblet Squat',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Kettlebell or Dumbbell',
  'body_part': 'Legs',
  'type': 'Compound',
  'muscle_groups_activated': 'Quadriceps, Glutes, Core, Upper Back',
  'instructions': 'Hold a kettlebell or dumbbell close to your chest with both hands. Stand with feet shoulder-width apart and brace your core. Sit down into a squat while keeping your elbows inside your knees if possible. Push through your heels to stand back up.'},
 {'id': 'hip-thrust-032',
  'exercise_name': 'Barbell Hip Thrust',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Barbell',
  'body_part': 'Glutes',
  'type': 'Compound',
  'muscle_groups_activated': 'Glutes, Hamstrings, Core',
  'instructions': 'Sit on the floor with your upper back against a bench and a barbell over your hips. Bend your knees and place your feet flat on the floor. Drive through your heels to lift your hips until your torso is parallel to the floor. Squeeze your glutes at the top, then lower with control.'},
 {'id': 'pallof-press-045',
  'exercise_name': 'Pallof Press',
  'type_of_activity': 'Strength',
  'type_of_equipment': 'Cable Machine',
  'body_part': 'Core',
  'type': 'Isolation',
  'muscle_groups_activated': 'Obliques, Rectus Abdominis, Glutes, Shoulders',
  'instructions': 'Stand sideways to a cable machine and hold the handle at chest level with both hands. Step away until there is tension on the cable. Press the handle straight out in front of your chest without letting your torso rotate. Bring it back in and repeat.'}]

# Define hit rate and mrr

In [35]:
# hit_rate = (number of queries where correct doc appears in results) / total queries
# MRR (Mean Reciprocal Rank) - When the correct doc does show up, how high up was it ranked?" — this rewards ranking quality, not just presence.

In [36]:
def hit_rate(relevance_total):
    cnt = 0

    for line in relevance_total:
        if True in line:
            cnt = cnt + 1

    return cnt / len(relevance_total)

def mrr(relevance_total):
    total_score = 0.0

    for line in relevance_total:
        for rank in range(len(line)):
            if line[rank] == True:
                total_score = total_score + 1 / (rank + 1)

    return total_score / len(relevance_total)

# Search Evaluation

In [37]:
# Define search function

In [38]:
def minsearch_search(query, boost=None):
    if boost is None: # no field is treated as more important than another
        boost = {}
    results = index.search(
        query=query,
        filter_dict={}, # no filtering. The search runs across everything in the index
        boost_dict=boost,
        num_results=10  # returns the top 10 matches.
    )
    return results

In [39]:
results

{'push-up-001': '[\n    "What are some effective bodyweight exercises I can do to strengthen my chest muscles?",\n    "Can you explain the proper technique for performing a push-up to ensure I don\'t injure myself?",\n    "What muscle groups are activated when doing push-ups, and how can they benefit my overall fitness?",\n    "Is there any special equipment needed to perform push-ups, or can they be done anywhere?",\n    "What are the benefits of incorporating compound exercises like push-ups into my strength training routine?"\n]',
 'bodyweight-squat-002': '[\n    "What are some effective bodyweight exercises I can do to strengthen my legs without any equipment?",\n    "Can you give me detailed instructions on how to perform a bodyweight squat correctly?",\n    "What muscle groups are activated when performing bodyweight squats?",\n    "Is the bodyweight squat considered a compound exercise, and if so, why?",\n    "How should I position my feet and body when doing bodyweight squats to avoid injury?"\n]',
 'plank-003': '["What is the correct way to perform a plank exercise for core strength?", "Can you tell me about the benefits of doing isometric exercises like the plank?", "What muscle groups are activated when doing a plank, and how does it help strengthen them?", "Do I need any equipment to do a plank exercise, and how do I ensure proper form?", "How long should I aim to hold a plank for optimal results, and what should I focus on during the exercise?"]',
 'lunges-004': '["What are some effective strength exercises that target my legs without the need for equipment?", "Can you explain how to properly perform a Forward Lunge for optimal results?", "What muscle groups are activated when doing Forward Lunges, and how do they contribute to leg strength?", "I want to add a compound exercise to my leg workout; how does the Forward Lunge fit into that category?", "What are the key form cues I should keep in mind to avoid injury while doing Forward Lunges?"]',
 'jumping-jacks-005': '["What are some effective bodyweight exercises I can do for a full-body workout?", "Can you provide instructions on how to perform Jumping Jacks correctly?", "What muscle groups are activated when doing Jumping Jacks?", "Is Jumping Jacks considered a cardio exercise, and what are its benefits?", "What type of equipment do I need to perform Jumping Jacks?"]',
 'glute-bridge-006': '["What is a good strength exercise I can do at home without any equipment that targets my glutes?", "Can you recommend a compound exercise that strengthens both my glutes and hamstrings?", "How do I properly perform a glute bridge to ensure I\'m using the right form?", "What muscle groups are activated when doing a glute bridge exercise?", "Is there a bodyweight exercise that effectively works on my core along with my glutes?"]',
 'pull-up-007': '["What are the proper instructions for performing a pull-up safely and effectively?", "Which muscles are primarily targeted when doing pull-ups?", "What type of exercise is a pull-up categorized as, and what equipment do I need?", "Can you explain how to perform a pull-up and what grip I should use?", "What body part do pull-ups mainly work, and what are the benefits of including them in my strength training routine?"]',
 'bicep-curl-008': '["What are some effective exercises I can do to target my biceps and forearms using dumbbells?", "Can you provide me with detailed instructions on how to perform a Dumbbell Bicep Curl?", "I\'m looking for strength training exercises for my arms; what would you recommend?", "What type of equipment do I need for a Dumbbell Bicep Curl, and how should I perform it?", "Which muscle groups are activated when I do Dumbbell Bicep Curls, and what is the best technique to use?"]',
 'shoulder-press-009': '["What is the correct technique for performing the Dumbbell Shoulder Press exercise?", "Which muscle groups are activated when I do the Dumbbell Shoulder Press?", "Can you give me the steps to safely perform a Dumbbell Shoulder Press?", "Is the Dumbbell Shoulder Press considered a compound exercise, and if so, why?", "What equipment do I need to perform the Dumbbell Shoulder Press effectively?"]',
 'bench-press-010': '[\n  "What is the proper technique for performing a Barbell Bench Press?",\n  "Which muscle groups are activated when doing a Barbell Bench Press?",\n  "What type of exercise is the Barbell Bench Press and what equipment do I need?",\n  "Can you provide me with instructions on how to safely perform a Barbell Bench Press?",\n  "Is the Barbell Bench Press a compound exercise, and what body parts does it target?"\n]',
 'deadlift-011': '[\n    "What are the proper instructions for performing a conventional deadlift using a barbell?",\n    "Can you tell me which muscle groups are activated when I do a conventional deadlift?",\n    "What type of equipment do I need for performing a conventional deadlift?",\n    "Is the conventional deadlift considered a compound exercise, and if so, what does that mean?",\n    "How do I safely and effectively perform a conventional deadlift while minimizing the risk of injury?"\n]',
 'barbell-squat-012': '["What is the proper technique for performing a Barbell Back Squat?", "Which muscle groups are worked when doing a Barbell Back Squat?", "What type of equipment do I need to perform a Barbell Back Squat?", "Can you explain how to safely execute the Barbell Back Squat for strength training?", "What body parts are primarily involved in the Barbell Back Squat exercise?"]',
 'romanian-deadlift-013': '[\n    "What are the steps I should follow to properly perform a Romanian Deadlift with a barbell?",\n    "Which muscle groups are activated when doing the Romanian Deadlift exercise?",\n    "Can you tell me about the equipment needed for a Romanian Deadlift workout?",\n    "Is the Romanian Deadlift a strength training exercise or a cardio exercise?",\n    "How do I ensure I\'m using the correct form while performing a Romanian Deadlift?"\n]',
 'lat-pulldown-014': '["What are the proper instructions for performing a lat pulldown exercise?", "Can you tell me which muscle groups are activated when doing a lat pulldown?", "What type of equipment do I need for a lat pulldown workout?", "Is the lat pulldown considered a compound exercise, and if so, why?", "What specific body part does the lat pulldown mainly target?"]',
 'leg-press-015': '["What is the best exercise for targeting my quadriceps and glutes?", "Can you provide instructions on how to properly use the leg press machine?", "What type of equipment do I need for a leg press workout?", "Is the leg press considered a compound exercise and what muscles does it work?", "How should my body be positioned when using the leg press for optimal safety and effectiveness?"]',
 'chest-fly-016': '["What is the proper technique for performing the Machine Chest Fly exercise?", "Can you explain how to use the chest fly machine for isolating my chest muscles?", "What muscle groups are activated when doing the Machine Chest Fly?", "What instructions should I follow to safely perform the chest fly exercise?", "Is the Machine Chest Fly suitable for strengthening the front deltoids as well as the chest?"]',
 'leg-extension-017': '["What is the leg extension exercise and how do I perform it correctly?", "Can you explain the main muscle groups targeted by leg extension workouts?", "What type of equipment do I need for the leg extension exercise?", "Is the leg extension considered a strength training exercise or a cardio workout?", "What are the steps involved in using the leg extension machine effectively?"]',
 'hamstring-curl-018': '[\n    "What is the proper technique for performing a seated hamstring curl on a machine?",\n    "What muscles are activated when using the seated hamstring curl machine?",\n    "Can you explain how to correctly use the hamstring curl machine for strengthening my hamstrings?",\n    "What type of exercise is a seated hamstring curl, and what equipment do I need for it?",\n    "How do I ensure I am working my hamstrings effectively while using a hamstring curl machine?"\n]',
 'seated-row-019': '["What is the correct way to perform a Seated Cable Row exercise?", "Which muscles are activated when doing a Seated Cable Row?", "What equipment do I need to do a Seated Cable Row exercise?", "Is the Seated Cable Row a compound exercise, and if so, what does that mean?", "Can you give me detailed instructions on how to do a Seated Cable Row properly?"]',
 'dips-020': '[\n    "What is the correct way to perform a Parallel Bar Dip for strengthening my chest and triceps?",\n    "Can you provide instructions on how to do the Parallel Bar Dip using parallel bars?",\n    "What muscle groups are activated when I do Parallel Bar Dips, and how can I focus on my chest?",\n    "I want to incorporate compound exercises into my strength training; how do I properly execute a Parallel Bar Dip?",\n    "What should I keep in mind regarding body positioning and form while performing Parallel Bar Dips?"\n]',
 'mountain-climber-021': '["What is a good bodyweight exercise I can do for my core that doesn\'t require any equipment?", "Can you explain how to perform the Mountain Climber exercise correctly?", "What muscle groups are activated when doing Mountain Climbers?", "Is Mountain Climber considered a cardio exercise, and how does it benefit my fitness?", "Could you give me a step-by-step guide on how to do Mountain Climbers for maximum effectiveness?"]',
 'burpee-022': '["What are the instructions for performing a burpee correctly?", "Can you tell me about the muscle groups targeted when doing burpees?", "Is a burpee considered a cardio exercise and what type of equipment do I need for it?", "What body parts does the burpee exercise work on?", "Can you explain the steps involved in doing a burpee as part of my workout routine?"]',
 'sit-up-023': '[\n    "What are the correct instructions for performing a sit-up exercise without any equipment?",\n    "Can you explain the muscle groups that are activated when doing sit-ups?",\n    "What type of activity is a sit-up considered, and how does it benefit my core strength?",\n    "Can I perform sit-ups safely at home, and what body position should I maintain during the exercise?",\n    "What is the difference between a sit-up and other core exercises in terms of muscle activation?"\n]',
 'russian-twist-024': '["What is a good exercise to strengthen my core muscles, particularly the obliques and rectus abdominis?", "Can you explain how to perform a Russian Twist correctly, including any tips for proper form?", "What type of equipment do I need to do a Russian Twist at home?", "Is the Russian Twist an effective isolation exercise for the core, and how do I make it more challenging?", "What muscles are activated when performing the Russian Twist exercise, and how does it benefit my core workout?"]',
 'calf-raise-025': '["What is the standing calf raise exercise, and how should I perform it correctly?", "Can you explain the muscles that are targeted by the standing calf raise?", "Is the standing calf raise a strength training activity, and do I need any equipment for it?", "What are the steps to execute a standing calf raise safely and effectively?", "Which part of the body does the standing calf raise primarily work on?"]',
 'lateral-raise-026': '["What is the best exercise for targeting my lateral deltoids and upper traps?", "Can you provide me with instructions for performing a Dumbbell Lateral Raise correctly?", "What type of equipment do I need for an isolation exercise that focuses on the shoulders?", "Could you explain how to correctly do a Dumbbell Lateral Raise without risking injury?", "Is the Dumbbell Lateral Raise a strength training exercise, and how does it benefit my shoulder muscles?"]',
 'rear-delt-fly-027': '["What is a good exercise to target the rear deltoids and improve shoulder strength?", "Can you provide instructions for performing the Dumbbell Rear Delt Fly safely?", "What type of equipment do I need to do the Dumbbell Rear Delt Fly exercise?", "Which muscle groups are activated when doing a Dumbbell Rear Delt Fly?", "Is the Dumbbell Rear Delt Fly an isolation exercise, and how should it be performed?"]',
 'tricep-pushdown-028': '[\n    "What is the correct way to perform a Cable Tricep Pushdown exercise?",\n    "Can you provide instructions for using a cable machine to strengthen my triceps?",\n    "What muscles will I be activating if I do Cable Tricep Pushdowns?",\n    "What type of equipment do I need to do a Cable Tricep Pushdown?",\n    "Is the Cable Tricep Pushdown an isolation exercise, and how does it target my arms?"\n]',
 'overhead-tricep-extension-029': '["What is the proper way to perform an Overhead Dumbbell Tricep Extension?", "Which muscle groups are activated when doing Overhead Dumbbell Tricep Extensions?", "Can you tell me what type of equipment I need for the Overhead Dumbbell Tricep Extension exercise?", "Is the Overhead Dumbbell Tricep Extension considered a strength exercise or a cardio exercise?", "What body parts are targeted by the Overhead Dumbbell Tricep Extension?"]',
 'farmer-carry-030': '["What is the Farmer\'s Carry exercise, and how should I perform it properly?", "Which muscle groups does the Farmer\'s Carry activate when I do it with dumbbells?", "Can you provide me with instructions on how to correctly execute a Farmer\'s Carry for strength training?", "What type of equipment do I need for the Farmer\'s Carry exercise, and what is the best way to set it up?", "Is the Farmer\'s Carry considered a compound exercise, and what body parts does it target?"]',
 'step-up-031': '["What is the correct way to perform a Step-Up exercise for leg strength?", "Can you explain how to do a Step-Up using a bench or box?", "What muscle groups are activated when doing a Step-Up exercise?", "What type of equipment do I need to perform a Step-Up?", "Is the Step-Up considered a compound exercise, and why?"]',
 'hip-thrust-032': '[\n    "What is the correct way to perform a Barbell Hip Thrust for optimal glute activation?",\n    "Can you provide me with instructions on how to do the Barbell Hip Thrust exercise safely?",\n    "What muscle groups are targeted when doing a Barbell Hip Thrust with a barbell?",\n    "I\'m looking to strengthen my glutes; how do I perform a Barbell Hip Thrust?",\n    "What equipment do I need to properly execute a Barbell Hip Thrust exercise?"\n]',
 'incline-bench-press-033': '["What is the best exercise to target my upper chest muscles using dumbbells?", "Can you provide detailed instructions for performing an incline dumbbell bench press?", "What muscle groups are activated when doing an incline dumbbell bench press?", "Is the incline dumbbell bench press a compound exercise, and what equipment do I need for it?", "How should I position my body and hands while doing the incline dumbbell bench press to ensure proper form?"]',
 'assisted-pull-up-034': '[\n    "What is the proper way to use the Assisted Pull-Up Machine for my back workouts?",\n    "Can you explain how to perform an Assisted Pull-Up correctly, including any specific techniques?",\n    "What muscle groups are activated when I use the Assisted Pull-Up Machine for strength training?",\n    "What adjustments should I make on the Assisted Pull-Up Machine to ensure I am pulling with the right amount of assistance?",\n    "Could you provide detailed instructions on how to execute an Assisted Pull-Up safely and effectively?"\n]',
 'ab-crunch-machine-035': '["What is the best machine exercise to target my core specifically?", "Can you explain how to properly use the ab crunch machine for effective results?", "Which muscle groups are activated when using the ab crunch machine?", "What type of exercise is the ab crunch machine classified as, and what is its primary focus?", "Are there any tips for avoiding injury while using the ab crunch machine?"]',
 'pec-deck-036': '["What is the correct way to perform a Pec Deck Fly exercise?", "Can you explain how to use the Pec Deck Fly machine for strength training?", "What muscle groups does the Pec Deck Fly primarily target during my workout?", "What type of exercise is the Pec Deck Fly classified as and what body part does it focus on?", "Are there specific instructions I should follow while using the Pec Deck Fly for isolation training?"]',
 'hack-squat-037': '["What is the correct way to perform a hack squat on the machine?", "Which muscle groups are primarily activated during a hack squat?", "What type of equipment do I need to perform a hack squat exercise?", "Is the hack squat considered a compound exercise or an isolation exercise?", "Can you provide the steps to properly use the hack squat machine for leg workouts?"]',
 'smith-machine-squat-038': '["What is the proper technique for performing a Smith Machine Squat?", "Which muscle groups are activated when doing a Smith Machine Squat?", "Can you provide me with instructions on how to safely perform a Smith Machine Squat?", "What type of workout does the Smith Machine Squat fall under?", "What body parts does the Smith Machine Squat primarily target?"]',
 'kettlebell-swing-039': '[\n    "What are the main muscle groups activated when performing a kettlebell swing?",\n    "Can you explain the correct form and technique for doing a kettlebell swing?",\n    "What type of exercise is a kettlebell swing, and what body parts does it work?",\n    "What equipment do I need to perform a kettlebell swing effectively?",\n    "Is the kettlebell swing considered a strength training exercise, and what are its benefits?"\n]',
 'goblet-squat-040': '["What is the Goblet Squat, and what type of exercise is it considered?", "Can you explain how to properly perform a Goblet Squat with a kettlebell or dumbbell?", "Which muscle groups are targeted when doing a Goblet Squat?", "What equipment do I need to perform a Goblet Squat effectively?", "Is the Goblet Squat a compound exercise, and what does that mean?"]',
 'incline-push-up-041': '["What is the best way to perform an incline push-up using a bench or box?", "Can you explain the proper technique for incline push-ups and which muscles they target?", "What equipment do I need to do incline push-ups effectively?", "How do incline push-ups differ from regular push-ups in terms of muscle activation?", "What body parts do incline push-ups primarily work on and how can I incorporate them into my strength training routine?"]',
 'wall-sit-042': '["What is a good bodyweight exercise I can do to strengthen my legs without any equipment?", "Can you explain how to properly perform a wall sit to avoid injury?", "What muscle groups are activated during a wall sit, and what benefits does it offer?", "How do I maintain proper form during a wall sit, and what should I focus on while holding the position?", "What type of exercise is a wall sit, and how does it fit into a strength training routine?"]',
 'superman-043': '["What is a good bodyweight exercise for strengthening my lower back and glutes?", "Can you explain how to properly perform the Superman exercise for isolating my back muscles?", "What are the main muscle groups activated when doing the Superman exercise?", "Is there any specific equipment needed for the Superman exercise, or can it be done with just my body weight?", "What steps should I follow to ensure I perform the Superman exercise correctly and safely?"]',
 'bird-dog-044': '["What is the Bird Dog exercise and how do I perform it correctly?", "Can you tell me which muscles are targeted when doing the Bird Dog exercise?", "Is the Bird Dog exercise suitable for beginners and what equipment do I need?", "What type of exercise is the Bird Dog and what body parts does it work on?", "How can I modify the Bird Dog exercise to make it easier or more challenging?"]',

In [40]:
# Now that we have ground truth data, we can evaluate how well our search retrieves the correct documents.
# For each question in our ground truth dataset (250 total) we run search. Then we check whether the results include the correct document.
# For search evaluation, we only need the search part of the RAG pipeline. We don't need to call the LLM yet.

In [41]:
def evaluate(ground_truth, search_function):
    relevance_total = []

    for item in tqdm(ground_truth):
        doc_id = item['id']
        results = search_function(item['question'])
        relevance = [d['id'] == doc_id for d in results] # take each item out of the results list, one at a time, and temporarily call it d while working with it."
        relevance_total.append(relevance)

    return {
        'hit_rate': hit_rate(relevance_total),
        'mrr': mrr(relevance_total),
    }

In [42]:
result = evaluate(ground_truth, lambda q: minsearch_search(q))
print(result)

  0%|          | 0/250 [00:00<?, ?it/s]

{'hit_rate': 0.996, 'mrr': 0.9479666666666667}

In [43]:
# finding the best boost_dict values guessing by hand and seeing how it influences the hit rate and mrr values

In [44]:
def minsearch_search2(query):
    boost = {"muscle_groups_activated": 2.0, "instructions": 0.5}

    results = index.search(
        query=query,
        filter_dict={},  # no filtering. The search runs across everything in the index
        boost_dict=boost,
        num_results=10 # returns the top 10 matches.
    )

    return results

In [45]:
result = evaluate(ground_truth, lambda q: minsearch_search2(q))
print(result)

  0%|          | 0/250 [00:00<?, ?it/s]

{'hit_rate': 0.996, 'mrr': 0.9492}

In [46]:
# finding the best boost_dict values without guessing by hand

In [47]:
# Given we have 7 boost fields (exercise_name, type_of_activity, type_of_equipment, body_part, type, muscle_groups_activated, instructions)
# grid search is impractical (too many combinations). Random search is the right tool here.

# Split the ground truth and implement random search to find best boost values

In [48]:
# This is a classic ML practice, applied here to search tuning: don't tune and evaluate on the same data.

In [49]:

# Validation set (first 100 questions) — used to search for the best boost parameters.
# Test set (remaining questions) — held back, untouched during tuning. Once you've picked your "best" boost params using validation data, you check performance on the test set once — this tells you how well your tuning generalizes, rather than just overfitting to quirks of the validation set.
# If you tuned and evaluated on the exact same 250 questions, you'd risk picking boost values that happen to work great on those specific questions but don't generalize — similar to overfitting in ML.

gt_val = ground_truth[:100]  
gt_test = ground_truth[100:] 

print(len(gt_val))   # 100
print(len(gt_test))  # 150

100
150

In [50]:
param_ranges = {
    'exercise_name': (0.0, 3.0),
    'type_of_activity': (0.0, 3.0),
    'type_of_equipment': (0.0, 3.0),
    'body_part': (0.0, 3.0),
    'type': (0.0, 3.0),
    'muscle_groups_activated': (0.0, 3.0),
    'instructions': (0.0, 3.0),
}

def objective(boost_params):
    def search_function(q):
        return minsearch_search(q, boost_params)

    results = evaluate(gt_val, search_function)
    return results['mrr']

In [51]:
import random # Bring in Python's built-in random module — needed for generating random numbers (random.randint, random.uniform).

def simple_optimize(param_ranges, objective_function, n_iterations=10): 
# param_ranges — a dict describing, for each parameter, the min/max bounds to search within.\
# objective_function — a function you hand in that takes one set of parameters and returns a score, it returns the MRR)
# n_iterations=10 — how many random guesses to try. =10 is a default value
    best_params = None # will eventually hold whichever parameter combination scored highest. Starts as None because nothing has been tried yet.
    best_score = float('-inf')  # negative infinity. This is a common trick: start your "best score so far" at the lowest possible value, so that literally any real score you compute will beat it
    for _ in range(n_iterations):
        # Generate random parameters
        current_params = {}
        for param, (min_val, max_val) in param_ranges.items(): # param = the key, (min_val, max_val) = the value, .items() lets you loop over a dictionary and get both the key and value together,
            if isinstance(min_val, int) and isinstance(max_val, int): # whole numbers and decimals need different random function, checks if min_val and max_val are int or not
                current_params[param] = random.randint(min_val, max_val)
            else:
                current_params[param] = random.uniform(min_val, max_val)
        
        # Evaluate the objective function
        current_score = objective_function(current_params)
        
        # Update best if current is better
        if current_score > best_score:  # Change to > if maximizing
            best_score = current_score
            best_params = current_params
    
    return best_params, best_score

In [52]:
simple_optimize(param_ranges, objective, n_iterations=20)

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

  0%|          | 0/100 [00:00<?, ?it/s]

({'exercise_name': 2.768256870486524,
  'type_of_activity': 2.5312179853263763,
  'type_of_equipment': 0.38323261618057813,
  'body_part': 2.6708588161697198,
  'type': 1.3359258110156391,
  'muscle_groups_activated': 1.246509232681984,
  'instructions': 0.8222473754907844},
 0.9686666666666668)

In [53]:
def minsearch_improved(query):
    boost = {
        'exercise_name': 2.53,
        'type_of_activity': 0.69,
        'type_of_equipment': 2.09,
        'body_part': 2.23,
        'type': 2.94,
        'muscle_groups_activated': 0.87,
        'instructions': 1.59
    }

    results = index.search(
        query=query,
        filter_dict={},
        boost_dict=boost,
        num_results=10
    )

    return results

evaluate(ground_truth, lambda q: minsearch_improved(q))

  0%|          | 0/250 [00:00<?, ?it/s]

{'hit_rate': 0.996, 'mrr': 0.9544666666666667}

# RAG Evaluation

In [54]:
print(ground_truth[0])

{'id': 'push-up-001', 'question': 'What are some effective bodyweight exercises I can do to strengthen my chest muscles?'}

In [55]:
print(documents[0])

{'id': 'push-up-001', 'exercise_name': 'Push-Up', 'type_of_activity': 'Strength', 'type_of_equipment': 'None (bodyweight)', 'body_part': 'Chest', 'type': 'Compound', 'muscle_groups_activated': 'Chest, Triceps, Shoulders, Core', 'instructions': 'Start in a plank position with hands slightly wider than shoulder-width apart. Keep your body in a straight line from head to heels. Lower your chest toward the floor by bending your elbows. Pause briefly, then push through your palms to return to the starting position. Repeat with controlled form.'}

In [78]:
question = 'Is the Lat Pulldown considered a strength training activity, and if so, why?'
answer = rag(question)
print(answer)

Yes, the Lat Pulldown is considered a strength training activity because it targets multiple muscle groups, including the lats, biceps, rhomboids, and rear deltoids, and is performed using a machine. It is categorized as a compound exercise, which involves the use of multiple joints and muscle groups, contributing to overall strength development in the back.

In [80]:
prompt_template = """

You're a fitness instructor. Answer the QUESTION based on the CONTEXT from our exercises database.
Use only the facts from the CONTEXT when answering the QUESTION.

Question:
{question}

Context:
{context}
"""

In [81]:
prompt2_template = """
You are an expert evaluator for a RAG system.
Your task is to analyze the relevance of the generated answer to the given question.
Based on the relevance of the generated answer, you will classify it
as "NON_RELEVANT", "PARTLY_RELEVANT", or "RELEVANT".

Here is the data for evaluation:

Question: {question}
Generated Answer: {answer_llm}

Please analyze the content and context of the generated answer in relation to the question
and provide your evaluation in parsable JSON without using code blocks:

{{
  "Relevance": "NON_RELEVANT" | "PARTLY_RELEVANT" | "RELEVANT",
  "Explanation": "[Provide a brief explanation for your evaluation]"
}}
""".strip()

In [82]:
ground_truth

[{'id': 'push-up-001',
  'question': 'What are some effective bodyweight exercises I can do to strengthen my chest muscles?'},
 {'id': 'push-up-001',
  'question': "Can you explain the proper technique for performing a push-up to ensure I don't injure myself?"},
 {'id': 'push-up-001',
  'question': 'What muscle groups are activated when doing push-ups, and how can they benefit my overall fitness?'},
 {'id': 'push-up-001',
  'question': 'Is there any special equipment needed to perform push-ups, or can they be done anywhere?'},
 {'id': 'push-up-001',
  'question': 'What are the benefits of incorporating compound exercises like push-ups into my strength training routine?'},
 {'id': 'bodyweight-squat-002',
  'question': 'What are some effective bodyweight exercises I can do to strengthen my legs without any equipment?'},
 {'id': 'bodyweight-squat-002',
  'question': 'Can you give me detailed instructions on how to perform a bodyweight squat correctly?'},
 {'id': 'bodyweight-squat-002',
  'question': 'What muscle groups are activated when performing bodyweight squats?'},
 {'id': 'bodyweight-squat-002',
  'question': 'Is the bodyweight squat considered a compound exercise, and if so, why?'},
 {'id': 'bodyweight-squat-002',
  'question': 'How should I position my feet and body when doing bodyweight squats to avoid injury?'},
 {'id': 'plank-003',
  'question': 'What is the correct way to perform a plank exercise for core strength?'},
 {'id': 'plank-003',
  'question': 'Can you tell me about the benefits of doing isometric exercises like the plank?'},
 {'id': 'plank-003',
  'question': 'What muscle groups are activated when doing a plank, and how does it help strengthen them?'},
 {'id': 'plank-003',
  'question': 'Do I need any equipment to do a plank exercise, and how do I ensure proper form?'},
 {'id': 'plank-003',
  'question': 'How long should I aim to hold a plank for optimal results, and what should I focus on during the exercise?'},
 {'id': 'lunges-004',
  'question': 'What are some effective strength exercises that target my legs without the need for equipment?'},
 {'id': 'lunges-004',
  'question': 'Can you explain how to properly perform a Forward Lunge for optimal results?'},
 {'id': 'lunges-004',
  'question': 'What muscle groups are activated when doing Forward Lunges, and how do they contribute to leg strength?'},
 {'id': 'lunges-004',
  'question': 'I want to add a compound exercise to my leg workout; how does the Forward Lunge fit into that category?'},
 {'id': 'lunges-004',
  'question': 'What are the key form cues I should keep in mind to avoid injury while doing Forward Lunges?'},
 {'id': 'jumping-jacks-005',
  'question': 'What are some effective bodyweight exercises I can do for a full-body workout?'},
 {'id': 'jumping-jacks-005',
  'question': 'Can you provide instructions on how to perform Jumping Jacks correctly?'},
 {'id': 'jumping-jacks-005',
  'question': 'What muscle groups are activated when doing Jumping Jacks?'},
 {'id': 'jumping-jacks-005',
  'question': 'Is Jumping Jacks considered a cardio exercise, and what are its benefits?'},
 {'id': 'jumping-jacks-005',
  'question': 'What type of equipment do I need to perform Jumping Jacks?'},
 {'id': 'glute-bridge-006',
  'question': 'What is a good strength exercise I can do at home without any equipment that targets my glutes?'},
 {'id': 'glute-bridge-006',
  'question': 'Can you recommend a compound exercise that strengthens both my glutes and hamstrings?'},
 {'id': 'glute-bridge-006',
  'question': "How do I properly perform a glute bridge to ensure I'm using the right form?"},
 {'id': 'glute-bridge-006',
  'question': 'What muscle groups are activated when doing a glute bridge exercise?'},
 {'id': 'glute-bridge-006',
  'question': 'Is there a bodyweight exercise that effectively works on my core along with my glutes?'},
 {'id': 'pull-up-007',
  'question': 'What are the proper instructions for performing a pull-up safely and effectively?'},
 {'id': 'pull-up-007',
  'question': 'Which muscles are primarily targeted when doing pull-ups?'},
 {'id': 'pull-up-007',
  'question': 'What type of exercise is a pull-up categorized as, and what equipment do I need?'},
 {'id': 'pull-up-007',
  'question': 'Can you explain how to perform a pull-up and what grip I should use?'},
 {'id': 'pull-up-007',
  'question': 'What body part do pull-ups mainly work, and what are the benefits of including them in my strength training routine?'},
 {'id': 'bicep-curl-008',
  'question': 'What are some effective exercises I can do to target my biceps and forearms using dumbbells?'},
 {'id': 'bicep-curl-008',
  'question': 'Can you provide me with detailed instructions on how to perform a Dumbbell Bicep Curl?'},
 {'id': 'bicep-curl-008',
  'question': "I'm looking for strength training exercises for my arms; what would you recommend?"},
 {'id': 'bicep-curl-008',
  'question': 'What type of equipment do I need for a Dumbbell Bicep Curl, and how should I perform it?'},
 {'id': 'bicep-curl-008',
  'question': 'Which muscle groups are activated when I do Dumbbell Bicep Curls, and what is the best technique to use?'},
 {'id': 'shoulder-press-009',
  'question': 'What is the correct technique for performing the Dumbbell Shoulder Press exercise?'},
 {'id': 'shoulder-press-009',
  'question': 'Which muscle groups are activated when I do the Dumbbell Shoulder Press?'},
 {'id': 'shoulder-press-009',
  'question': 'Can you give me the steps to safely perform a Dumbbell Shoulder Press?'},
 {'id': 'shoulder-press-009',
  'question': 'Is the Dumbbell Shoulder Press considered a compound exercise, and if so, why?'},
 {'id': 'shoulder-press-009',
  'question': 'What equipment do I need to perform the Dumbbell Shoulder Press effectively?'},
 {'id': 'bench-press-010',
  'question': 'What is the proper technique for performing a Barbell Bench Press?'},
 {'id': 'bench-press-010',
  'question': 'Which muscle groups are activated when doing a Barbell Bench Press?'},
 {'id': 'bench-press-010',
  'question': 'What type of exercise is the Barbell Bench Press and what equipment do I need?'},
 {'id': 'bench-press-010',
  'question': 'Can you provide me with instructions on how to safely perform a Barbell Bench Press?'},
 {'id': 'bench-press-010',
  'question': 'Is the Barbell Bench Press a compound exercise, and what body parts does it target?'},
 {'id': 'deadlift-011',
  'question': 'What are the proper instructions for performing a conventional deadlift using a barbell?'},
 {'id': 'deadlift-011',
  'question': 'Can you tell me which muscle groups are activated when I do a conventional deadlift?'},
 {'id': 'deadlift-011',
  'question': 'What type of equipment do I need for performing a conventional deadlift?'},
 {'id': 'deadlift-011',
  'question': 'Is the conventional deadlift considered a compound exercise, and if so, what does that mean?'},
 {'id': 'deadlift-011',
  'question': 'How do I safely and effectively perform a conventional deadlift while minimizing the risk of injury?'},
 {'id': 'barbell-squat-012',
  'question': 'What is the proper technique for performing a Barbell Back Squat?'},
 {'id': 'barbell-squat-012',
  'question': 'Which muscle groups are worked when doing a Barbell Back Squat?'},
 {'id': 'barbell-squat-012',
  'question': 'What type of equipment do I need to perform a Barbell Back Squat?'},
 {'id': 'barbell-squat-012',
  'question': 'Can you explain how to safely execute the Barbell Back Squat for strength training?'},
 {'id': 'barbell-squat-012',
  'question': 'What body parts are primarily involved in the Barbell Back Squat exercise?'},
 {'id': 'romanian-deadlift-013',
  'question': 'What are the steps I should follow to properly perform a Romanian Deadlift with a barbell?'},
 {'id': 'romanian-deadlift-013',
  'question': 'Which muscle groups are activated when doing the Romanian Deadlift exercise?'},
 {'id': 'romanian-deadlift-013',
  'question': 'Can you tell me about the equipment needed for a Romanian Deadlift workout?'},
 {'id': 'romanian-deadlift-013',
  'question': 'Is the Romanian Deadlift a strength training exercise or a cardio exercise?'},
 {'id': 'romanian-deadlift-013',
  'question': "How do I ensure I'm using the correct form while performing a Romanian Deadlift?"},
 {'id': 'lat-pulldown-014',
  'question': 'What are the proper instructions for performing a lat pulldown exercise?'},
 {'id': 'lat-pulldown-014',
  'question': 'Can you tell me which muscle groups are activated when doing a lat pulldown?'},
 {'id': 'lat-pulldown-014',
  'question': 'What type of equipment do I need for a lat pulldown workout?'},
 {'id': 'lat-pulldown-014',
  'question': 'Is the lat pulldown considered a compound exercise, and if so, why?'},
 {'id': 'lat-pulldown-014',
  'question': 'What specific body part does the lat pulldown mainly target?'},
 {'id': 'leg-press-015',
  'question': 'What is the best exercise for targeting my quadriceps and glutes?'},
 {'id': 'leg-press-015',
  'question': 'Can you provide instructions on how to properly use the leg press machine?'},
 {'id': 'leg-press-015',
  'question': 'What type of equipment do I need for a leg press workout?'},
 {'id': 'leg-press-015',
  'question': 'Is the leg press considered a compound exercise and what muscles does it work?'},
 {'id': 'leg-press-015',
  'question': 'How should my body be positioned when using the leg press for optimal safety and effectiveness?'},
 {'id': 'chest-fly-016',
  'question': 'What is the proper technique for performing the Machine Chest Fly exercise?'},
 {'id': 'chest-fly-016',
  'question': 'Can you explain how to use the chest fly machine for isolating my chest muscles?'},
 {'id': 'chest-fly-016',
  'question': 'What muscle groups are activated when doing the Machine Chest Fly?'},
 {'id': 'chest-fly-016',
  'question': 'What instructions should I follow to safely perform the chest fly exercise?'},
 {'id': 'chest-fly-016',
  'question': 'Is the Machine Chest Fly suitable for strengthening the front deltoids as well as the chest?'},
 {'id': 'leg-extension-017',
  'question': 'What is the leg extension exercise and how do I perform it correctly?'},
 {'id': 'leg-extension-017',
  'question': 'Can you explain the main muscle groups targeted by leg extension workouts?'},
 {'id': 'leg-extension-017',
  'question': 'What type of equipment do I need for the leg extension exercise?'},
 {'id': 'leg-extension-017',
  'question': 'Is the leg extension considered a strength training exercise or a cardio workout?'},
 {'id': 'leg-extension-017',
  'question': 'What are the steps involved in using the leg extension machine effectively?'},
 {'id': 'hamstring-curl-018',
  'question': 'What is the proper technique for performing a seated hamstring curl on a machine?'},
 {'id': 'hamstring-curl-018',
  'question': 'What muscles are activated when using the seated hamstring curl machine?'},
 {'id': 'hamstring-curl-018',
  'question': 'Can you explain how to correctly use the hamstring curl machine for strengthening my hamstrings?'},
 {'id': 'hamstring-curl-018',
  'question': 'What type of exercise is a seated hamstring curl, and what equipment do I need for it?'},
 {'id': 'hamstring-curl-018',
  'question': 'How do I ensure I am working my hamstrings effectively while using a hamstring curl machine?'},
 {'id': 'seated-row-019',
  'question': 'What is the correct way to perform a Seated Cable Row exercise?'},
 {'id': 'seated-row-019',
  'question': 'Which muscles are activated when doing a Seated Cable Row?'},
 {'id': 'seated-row-019',
  'question': 'What equipment do I need to do a Seated Cable Row exercise?'},
 {'id': 'seated-row-019',
  'question': 'Is the Seated Cable Row a compound exercise, and if so, what does that mean?'},
 {'id': 'seated-row-019',
  'question': 'Can you give me detailed instructions on how to do a Seated Cable Row properly?'},
 {'id': 'dips-020',
  'question': 'What is the correct way to perform a Parallel Bar Dip for strengthening my chest and triceps?'},
 {'id': 'dips-020',
  'question': 'Can you provide instructions on how to do the Parallel Bar Dip using parallel bars?'},
 {'id': 'dips-020',
  'question': 'What muscle groups are activated when I do Parallel Bar Dips, and how can I focus on my chest?'},
 {'id': 'dips-020',
  'question': 'I want to incorporate compound exercises into my strength training; how do I properly execute a Parallel Bar Dip?'},
 {'id': 'dips-020',
  'question': 'What should I keep in mind regarding body positioning and form while performing Parallel Bar Dips?'},
 {'id': 'mountain-climber-021',
  'question': "What is a good bodyweight exercise I can do for my core that doesn't require any equipment?"},
 {'id': 'mountain-climber-021',
  'question': 'Can you explain how to perform the Mountain Climber exercise correctly?'},
 {'id': 'mountain-climber-021',
  'question': 'What muscle groups are activated when doing Mountain Climbers?'},
 {'id': 'mountain-climber-021',
  'question': 'Is Mountain Climber considered a cardio exercise, and how does it benefit my fitness?'},
 {'id': 'mountain-climber-021',
  'question': 'Could you give me a step-by-step guide on how to do Mountain Climbers for maximum effectiveness?'},
 {'id': 'burpee-022',
  'question': 'What are the instructions for performing a burpee correctly?'},
 {'id': 'burpee-022',
  'question': 'Can you tell me about the muscle groups targeted when doing burpees?'},
 {'id': 'burpee-022',
  'question': 'Is a burpee considered a cardio exercise and what type of equipment do I need for it?'},
 {'id': 'burpee-022',
  'question': 'What body parts does the burpee exercise work on?'},
 {'id': 'burpee-022',
  'question': 'Can you explain the steps involved in doing a burpee as part of my workout routine?'},
 {'id': 'sit-up-023',
  'question': 'What are the correct instructions for performing a sit-up exercise without any equipment?'},
 {'id': 'sit-up-023',
  'question': 'Can you explain the muscle groups that are activated when doing sit-ups?'},
 {'id': 'sit-up-023',
  'question': 'What type of activity is a sit-up considered, and how does it benefit my core strength?'},
 {'id': 'sit-up-023',
  'question': 'Can I perform sit-ups safely at home, and what body position should I maintain during the exercise?'},
 {'id': 'sit-up-023',
  'question': 'What is the difference between a sit-up and other core exercises in terms of muscle activation?'},
 {'id': 'russian-twist-024',
  'question': 'What is a good exercise to strengthen my core muscles, particularly the obliques and rectus abdominis?'},
 {'id': 'russian-twist-024',
  'question': 'Can you explain how to perform a Russian Twist correctly, including any tips for proper form?'},
 {'id': 'russian-twist-024',
  'question': 'What type of equipment do I need to do a Russian Twist at home?'},
 {'id': 'russian-twist-024',
  'question': 'Is the Russian Twist an effective isolation exercise for the core, and how do I make it more challenging?'},
 {'id': 'russian-twist-024',
  'question': 'What muscles are activated when performing the Russian Twist exercise, and how does it benefit my core workout?'},
 {'id': 'calf-raise-025',
  'question': 'What is the standing calf raise exercise, and how should I perform it correctly?'},
 {'id': 'calf-raise-025',
  'question': 'Can you explain the muscles that are targeted by the standing calf raise?'},
 {'id': 'calf-raise-025',
  'question': 'Is the standing calf raise a strength training activity, and do I need any equipment for it?'},
 {'id': 'calf-raise-025',
  'question': 'What are the steps to execute a standing calf raise safely and effectively?'},
 {'id': 'calf-raise-025',
  'question': 'Which part of the body does the standing calf raise primarily work on?'},
 {'id': 'lateral-raise-026',
  'question': 'What is the best exercise for targeting my lateral deltoids and upper traps?'},
 {'id': 'lateral-raise-026',
  'question': 'Can you provide me with instructions for performing a Dumbbell Lateral Raise correctly?'},
 {'id': 'lateral-raise-026',
  'question': 'What type of equipment do I need for an isolation exercise that focuses on the shoulders?'},
 {'id': 'lateral-raise-026',
  'question': 'Could you explain how to correctly do a Dumbbell Lateral Raise without risking injury?'},
 {'id': 'lateral-raise-026',
  'question': 'Is the Dumbbell Lateral Raise a strength training exercise, and how does it benefit my shoulder muscles?'},
 {'id': 'rear-delt-fly-027',
  'question': 'What is a good exercise to target the rear deltoids and improve shoulder strength?'},
 {'id': 'rear-delt-fly-027',
  'question': 'Can you provide instructions for performing the Dumbbell Rear Delt Fly safely?'},
 {'id': 'rear-delt-fly-027',
  'question': 'What type of equipment do I need to do the Dumbbell Rear Delt Fly exercise?'},
 {'id': 'rear-delt-fly-027',
  'question': 'Which muscle groups are activated when doing a Dumbbell Rear Delt Fly?'},
 {'id': 'rear-delt-fly-027',
  'question': 'Is the Dumbbell Rear Delt Fly an isolation exercise, and how should it be performed?'},
 {'id': 'tricep-pushdown-028',
  'question': 'What is the correct way to perform a Cable Tricep Pushdown exercise?'},
 {'id': 'tricep-pushdown-028',
  'question': 'Can you provide instructions for using a cable machine to strengthen my triceps?'},
 {'id': 'tricep-pushdown-028',
  'question': 'What muscles will I be activating if I do Cable Tricep Pushdowns?'},
 {'id': 'tricep-pushdown-028',
  'question': 'What type of equipment do I need to do a Cable Tricep Pushdown?'},
 {'id': 'tricep-pushdown-028',
  'question': 'Is the Cable Tricep Pushdown an isolation exercise, and how does it target my arms?'},
 {'id': 'overhead-tricep-extension-029',
  'question': 'What is the proper way to perform an Overhead Dumbbell Tricep Extension?'},
 {'id': 'overhead-tricep-extension-029',
  'question': 'Which muscle groups are activated when doing Overhead Dumbbell Tricep Extensions?'},
 {'id': 'overhead-tricep-extension-029',
  'question': 'Can you tell me what type of equipment I need for the Overhead Dumbbell Tricep Extension exercise?'},
 {'id': 'overhead-tricep-extension-029',
  'question': 'Is the Overhead Dumbbell Tricep Extension considered a strength exercise or a cardio exercise?'},
 {'id': 'overhead-tricep-extension-029',
  'question': 'What body parts are targeted by the Overhead Dumbbell Tricep Extension?'},
 {'id': 'farmer-carry-030',
  'question': "What is the Farmer's Carry exercise, and how should I perform it properly?"},
 {'id': 'farmer-carry-030',
  'question': "Which muscle groups does the Farmer's Carry activate when I do it with dumbbells?"},
 {'id': 'farmer-carry-030',
  'question': "Can you provide me with instructions on how to correctly execute a Farmer's Carry for strength training?"},
 {'id': 'farmer-carry-030',
  'question': "What type of equipment do I need for the Farmer's Carry exercise, and what is the best way to set it up?"},
 {'id': 'farmer-carry-030',
  'question': "Is the Farmer's Carry considered a compound exercise, and what body parts does it target?"},
 {'id': 'step-up-031',
  'question': 'What is the correct way to perform a Step-Up exercise for leg strength?'},
 {'id': 'step-up-031',
  'question': 'Can you explain how to do a Step-Up using a bench or box?'},
 {'id': 'step-up-031',
  'question': 'What muscle groups are activated when doing a Step-Up exercise?'},
 {'id': 'step-up-031',
  'question': 'What type of equipment do I need to perform a Step-Up?'},
 {'id': 'step-up-031',
  'question': 'Is the Step-Up considered a compound exercise, and why?'},
 {'id': 'hip-thrust-032',
  'question': 'What is the correct way to perform a Barbell Hip Thrust for optimal glute activation?'},
 {'id': 'hip-thrust-032',
  'question': 'Can you provide me with instructions on how to do the Barbell Hip Thrust exercise safely?'},
 {'id': 'hip-thrust-032',
  'question': 'What muscle groups are targeted when doing a Barbell Hip Thrust with a barbell?'},
 {'id': 'hip-thrust-032',

In [83]:
ground_truth [0]

{'id': 'push-up-001',
 'question': 'What are some effective bodyweight exercises I can do to strengthen my chest muscles?'}

In [84]:
len(ground_truth)

250

In [85]:
df_sample = df_ground_truth.sample(n=100, random_state=1)

In [86]:
df_sample

,id,question
67,lat-pulldown-014,What type of equipment do I need for a lat pul...
249,donkey-kick-050,Could you provide step-by-step instructions fo...
230,sled-push-047,What is the Sled Push exercise and what type o...
161,incline-bench-press-033,Can you provide detailed instructions for perf...
91,seated-row-019,Which muscles are activated when doing a Seate...
...,...,...
17,lunges-004,What muscle groups are activated when doing Fo...
5,bodyweight-squat-002,What are some effective bodyweight exercises I...
185,smith-machine-squat-038,What is the proper technique for performing a ...
106,burpee-022,Can you tell me about the muscle groups target...
48,bench-press-010,Can you provide me with instructions on how to...

In [87]:
sample = df_sample.to_dict(orient='records')

In [88]:
sample

[{'id': 'lat-pulldown-014',
  'question': 'What type of equipment do I need for a lat pulldown workout?'},
 {'id': 'donkey-kick-050',
  'question': "Could you provide step-by-step instructions for the Donkey Kick to ensure I'm maximizing my workout?"},
 {'id': 'sled-push-047',
  'question': 'What is the Sled Push exercise and what type of activity is it considered?'},
 {'id': 'incline-bench-press-033',
  'question': 'Can you provide detailed instructions for performing an incline dumbbell bench press?'},
 {'id': 'seated-row-019',
  'question': 'Which muscles are activated when doing a Seated Cable Row?'},
 {'id': 'pallof-press-045',
  'question': 'What body parts are activated when I do the Pallof Press on a cable machine?'},
 {'id': 'barbell-squat-012',
  'question': 'Can you explain how to safely execute the Barbell Back Squat for strength training?'},
 {'id': 'sled-push-047',
  'question': 'How can I maintain good form while doing the Sled Push to avoid injury?'},
 {'id': 'hack-squat-037',
  'question': 'What is the correct way to perform a hack squat on the machine?'},
 {'id': 'push-up-001',
  'question': 'What are the benefits of incorporating compound exercises like push-ups into my strength training routine?'},
 {'id': 'trx-row-049',
  'question': 'Can you explain the proper form for a TRX Row using a suspension trainer?'},
 {'id': 'smith-machine-squat-038',
  'question': 'What type of workout does the Smith Machine Squat fall under?'},
 {'id': 'russian-twist-024',
  'question': 'Can you explain how to perform a Russian Twist correctly, including any tips for proper form?'},
 {'id': 'hack-squat-037',
  'question': 'What type of equipment do I need to perform a hack squat exercise?'},
 {'id': 'lateral-raise-026',
  'question': 'What type of equipment do I need for an isolation exercise that focuses on the shoulders?'},
 {'id': 'chest-fly-016',
  'question': 'What instructions should I follow to safely perform the chest fly exercise?'},
 {'id': 'hack-squat-037',
  'question': 'Can you provide the steps to properly use the hack squat machine for leg workouts?'},
 {'id': 'deadlift-011',
  'question': 'Can you tell me which muscle groups are activated when I do a conventional deadlift?'},
 {'id': 'glute-bridge-006',
  'question': "How do I properly perform a glute bridge to ensure I'm using the right form?"},
 {'id': 'leg-press-015',
  'question': 'Is the leg press considered a compound exercise and what muscles does it work?'},
 {'id': 'face-pull-046',
  'question': 'What is the proper technique for performing a Cable Face Pull to ensure I activate my shoulder muscles correctly?'},
 {'id': 'pull-up-007',
  'question': 'What body part do pull-ups mainly work, and what are the benefits of including them in my strength training routine?'},
 {'id': 'dips-020',
  'question': 'What is the correct way to perform a Parallel Bar Dip for strengthening my chest and triceps?'},
 {'id': 'smith-machine-squat-038',
  'question': 'Which muscle groups are activated when doing a Smith Machine Squat?'},
 {'id': 'calf-raise-025',
  'question': 'What is the standing calf raise exercise, and how should I perform it correctly?'},
 {'id': 'russian-twist-024',
  'question': 'What muscles are activated when performing the Russian Twist exercise, and how does it benefit my core workout?'},
 {'id': 'donkey-kick-050',
  'question': 'Can you tell me about a strength exercise that focuses on isolating the glutes without using any equipment?'},
 {'id': 'battle-ropes-048',
  'question': 'What are some effective instructions for incorporating battle ropes into my fitness routine?'},
 {'id': 'bicep-curl-008',
  'question': 'What type of equipment do I need for a Dumbbell Bicep Curl, and how should I perform it?'},
 {'id': 'bird-dog-044',
  'question': 'Can you tell me which muscles are targeted when doing the Bird Dog exercise?'},
 {'id': 'face-pull-046',
  'question': 'Can you explain the muscle groups that are targeted when using a Cable Machine for the Face Pull exercise?'},
 {'id': 'shoulder-press-009',
  'question': 'What equipment do I need to perform the Dumbbell Shoulder Press effectively?'},
 {'id': 'romanian-deadlift-013',
  'question': 'Can you tell me about the equipment needed for a Romanian Deadlift workout?'},
 {'id': 'wall-sit-042',
  'question': 'How do I maintain proper form during a wall sit, and what should I focus on while holding the position?'},
 {'id': 'incline-bench-press-033',
  'question': 'What is the best exercise to target my upper chest muscles using dumbbells?'},
 {'id': 'face-pull-046',
  'question': 'How does the Cable Face Pull exercise benefit my rear delts and overall shoulder stability?'},
 {'id': 'bicep-curl-008',
  'question': 'Which muscle groups are activated when I do Dumbbell Bicep Curls, and what is the best technique to use?'},
 {'id': 'pull-up-007',
  'question': 'Which muscles are primarily targeted when doing pull-ups?'},
 {'id': 'lunges-004',
  'question': 'I want to add a compound exercise to my leg workout; how does the Forward Lunge fit into that category?'},
 {'id': 'battle-ropes-048',
  'question': 'Can you explain the muscle groups that are activated while using battle ropes?'},
 {'id': 'wall-sit-042',
  'question': 'What is a good bodyweight exercise I can do to strengthen my legs without any equipment?'},
 {'id': 'lunges-004',
  'question': 'What are the key form cues I should keep in mind to avoid injury while doing Forward Lunges?'},
 {'id': 'seated-row-019',
  'question': 'Is the Seated Cable Row a compound exercise, and if so, what does that mean?'},
 {'id': 'mountain-climber-021',
  'question': 'What muscle groups are activated when doing Mountain Climbers?'},
 {'id': 'pull-up-007',
  'question': 'Can you explain how to perform a pull-up and what grip I should use?'},
 {'id': 'sit-up-023',
  'question': 'What are the correct instructions for performing a sit-up exercise without any equipment?'},
 {'id': 'bicep-curl-008',
  'question': 'What are some effective exercises I can do to target my biceps and forearms using dumbbells?'},
 {'id': 'plank-003',
  'question': 'Can you tell me about the benefits of doing isometric exercises like the plank?'},
 {'id': 'glute-bridge-006',
  'question': 'Is there a bodyweight exercise that effectively works on my core along with my glutes?'},
 {'id': 'push-up-001',
  'question': 'What are some effective bodyweight exercises I can do to strengthen my chest muscles?'},
 {'id': 'face-pull-046',
  'question': 'Are there any specific instructions I should follow to avoid injury while doing Cable Face Pulls?'},
 {'id': 'hamstring-curl-018',
  'question': 'What is the proper technique for performing a seated hamstring curl on a machine?'},
 {'id': 'sit-up-023',
  'question': 'What type of activity is a sit-up considered, and how does it benefit my core strength?'},
 {'id': 'farmer-carry-030',
  'question': "What type of equipment do I need for the Farmer's Carry exercise, and what is the best way to set it up?"},
 {'id': 'ab-crunch-machine-035',
  'question': 'Can you explain how to properly use the ab crunch machine for effective results?'},
 {'id': 'russian-twist-024',
  'question': 'What type of equipment do I need to do a Russian Twist at home?'},
 {'id': 'russian-twist-024',
  'question': 'Is the Russian Twist an effective isolation exercise for the core, and how do I make it more challenging?'},
 {'id': 'glute-bridge-006',
  'question': 'What muscle groups are activated when doing a glute bridge exercise?'},
 {'id': 'lunges-004',
  'question': 'Can you explain how to properly perform a Forward Lunge for optimal results?'},
 {'id': 'rear-delt-fly-027',
  'question': 'What is a good exercise to target the rear deltoids and improve shoulder strength?'},
 {'id': 'hack-squat-037',
  'question': 'Which muscle groups are primarily activated during a hack squat?'},
 {'id': 'step-up-031',
  'question': 'What is the correct way to perform a Step-Up exercise for leg strength?'},
 {'id': 'ab-crunch-machine-035',
  'question': 'Which muscle groups are activated when using the ab crunch machine?'},
 {'id': 'smith-machine-squat-038',
  'question': 'What body parts does the Smith Machine Squat primarily target?'},
 {'id': 'bench-press-010',
  'question': 'What type of exercise is the Barbell Bench Press and what equipment do I need?'},
 {'id': 'goblet-squat-040',
  'question': 'Which muscle groups are targeted when doing a Goblet Squat?'},
 {'id': 'shoulder-press-009',
  'question': 'What is the correct technique for performing the Dumbbell Shoulder Press exercise?'},
 {'id': 'assisted-pull-up-034',
  'question': 'What adjustments should I make on the Assisted Pull-Up Machine to ensure I am pulling with the right amount of assistance?'},
 {'id': 'tricep-pushdown-028',
  'question': 'What type of equipment do I need to do a Cable Tricep Pushdown?'},
 {'id': 'lat-pulldown-014',
  'question': 'What specific body part does the lat pulldown mainly target?'},
 {'id': 'hamstring-curl-018',
  'question': 'How do I ensure I am working my hamstrings effectively while using a hamstring curl machine?'},
 {'id': 'sled-push-047',
  'question': 'What instructions should I follow to properly execute a Sled Push?'},
 {'id': 'pec-deck-036',
  'question': 'Can you explain how to use the Pec Deck Fly machine for strength training?'},
 {'id': 'smith-machine-squat-038',
  'question': 'Can you provide me with instructions on how to safely perform a Smith Machine Squat?'},
 {'id': 'pec-deck-036',
  'question': 'Are there specific instructions I should follow while using the Pec Deck Fly for isolation training?'},
 {'id': 'barbell-squat-012',
  'question': 'What body parts are primarily involved in the Barbell Back Squat exercise?'},
 {'id': 'hamstring-curl-018',
  'question': 'What type of exercise is a seated hamstring curl, and what equipment do I need for it?'},
 {'id': 'trx-row-049',
  'question': 'What are the steps to properly perform a TRX Row for back strength?'},
 {'id': 'goblet-squat-040',
  'question': 'Is the Goblet Squat a compound exercise, and what does that mean?'},
 {'id': 'wall-sit-042',
  'question': 'What muscle groups are activated during a wall sit, and what benefits does it offer?'},
 {'id': 'seated-row-019',
  'question': 'What is the correct way to perform a Seated Cable Row exercise?'},
 {'id': 'plank-003',
  'question': 'How long should I aim to hold a plank for optimal results, and what should I focus on during the exercise?'},
 {'id': 'hip-thrust-032',
  'question': 'What equipment do I need to properly execute a Barbell Hip Thrust exercise?'},
 {'id': 'jumping-jacks-005',
  'question': 'Can you provide instructions on how to perform Jumping Jacks correctly?'},
 {'id': 'barbell-squat-012',
  'question': 'Which muscle groups are worked when doing a Barbell Back Squat?'},
 {'id': 'pallof-press-045',
  'question': 'What type of equipment do I need to perform the Pallof Press exercise?'},
 {'id': 'barbell-squat-012',
  'question': 'What is the proper technique for performing a Barbell Back Squat?'},
 {'id': 'burpee-022',
  'question': 'Is a burpee considered a cardio exercise and what type of equipment do I need for it?'},
 {'id': 'leg-extension-017',
  'question': 'What are the steps involved in using the leg extension machine effectively?'},
 {'id': 'deadlift-011',
  'question': 'Is the conventional deadlift considered a compound exercise, and if so, what does that mean?'},
 {'id': 'rear-delt-fly-027',
  'question': 'What type of equipment do I need to do the Dumbbell Rear Delt Fly exercise?'},
 {'id': 'pec-deck-036',
  'question': 'What muscle groups does the Pec Deck Fly primarily target during my workout?'},
 {'id': 'dips-020',
  'question': 'What should I keep in mind regarding body positioning and form while performing Parallel Bar Dips?'},
 {'id': 'calf-raise-025',
  'question': 'Is the standing calf raise a strength training activity, and do I need any equipment for it?'},
 {'id': 'shoulder-press-009',
  'question': 'Can you give me the steps to safely perform a Dumbbell Shoulder Press?'},
 {'id': 'lunges-004',
  'question': 'What muscle groups are activated when doing Forward Lunges, and how do they contribute to leg strength?'},
 {'id': 'bodyweight-squat-002',
  'question': 'What are some effective bodyweight exercises I can do to strengthen my legs without any equipment?'},
 {'id': 'smith-machine-squat-038',
  'question': 'What is the proper technique for performing a Smith Machine Squat?'},
 {'id': 'burpee-022',
  'question': 'Can you tell me about the muscle groups targeted when doing burpees?'},
 {'id': 'bench-press-010',
  'question': 'Can you provide me with instructions on how to safely perform a Barbell Bench Press?'}]

In [89]:
# The context is a formatted string with all the search results:

def build_context(results):
    lines = []
    for r in results:
        entry = (
            f"exercise_name: {r['exercise_name']}\n"
            f"type_of_activity: {r['type_of_activity']}\n"
            f"type_of_equipment: {r['type_of_equipment']}\n"
            f"body_part: {r['body_part']}\n"
            f"type: {r['type']}\n"
            f"muscle_groups_activated: {r['muscle_groups_activated']}\n"
            f"instructions: {r['instructions']}"
        )
        lines.append(entry)
    context = "\n\n".join(lines)
    return context

In [90]:
def build_prompt(query, results):
    context = build_context(results)
    prompt = prompt_template.format(question=query, context=context)
    return prompt.strip()

In [91]:
from dotenv import load_dotenv
load_dotenv()

from openai import OpenAI
openai_client = OpenAI()

In [92]:
def llm(prompt, model='gpt-4o-mini'):
    response = openai_client.chat.completions.create(
        model=model,
        messages=[{"role": "user", "content": prompt}]  
    )
    return response.choices[0].message.content

In [93]:
def rag(query, model='gpt-4o-mini'):
    search_results = minsearch_search(query)
    prompt = build_prompt(query, search_results)
    #print(prompt)
    answer = llm(prompt, model=model)
    return answer

In [94]:
from tqdm.auto import tqdm

In [95]:
evaluations = []

for record in tqdm(sample):
    question = record['question']
    answer_llm = rag(question) 

    prompt = prompt2_template.format(
        question=question,
        answer_llm=answer_llm
    )

    evaluation = llm(prompt)
    evaluation = json.loads(evaluation)

    evaluations.append((record, answer_llm, evaluation))

  0%|          | 0/100 [00:00<?, ?it/s]

In [96]:
df_eval = pd.DataFrame(evaluations, columns=['record', 'answer', 'evaluation'])

df_eval['id'] = df_eval.record.apply(lambda d: d['id'])
df_eval['question'] = df_eval.record.apply(lambda d: d['question'])

df_eval['relevance'] = df_eval.evaluation.apply(lambda d: d['Relevance'])
df_eval['explanation'] = df_eval.evaluation.apply(lambda d: d['Explanation'])

del df_eval['record']
del df_eval['evaluation']

In [97]:
df_eval.relevance.value_counts(normalize=True)

relevance
RELEVANT           0.93
PARTLY_RELEVANT    0.06
NON_RELEVANT       0.01
Name: proportion, dtype: float64

In [98]:
df_eval.to_csv('../data/rag-eval-gpt-4o-mini.csv', index=False)

In [99]:
df_eval[df_eval.relevance == 'NON_RELEVANT']

,answer,id,question,relevance,explanation
98,The context provided does not include informat...,burpee-022,Can you tell me about the muscle groups target...,NON_RELEVANT,The generated answer does not address the ques...

In [100]:
df_eval[df_eval.relevance == 'PARTLY_RELEVANT']

,answer,id,question,relevance,explanation
31,To perform the Dumbbell Shoulder Press effecti...,shoulder-press-009,What equipment do I need to perform the Dumbbe...,PARTLY_RELEVANT,The generated answer identifies a key piece of...
32,"For a Romanian Deadlift workout, the equipment...",romanian-deadlift-013,Can you tell me about the equipment needed for...,PARTLY_RELEVANT,"The generated answer mentions a barbell, which..."
55,"To do a Russian Twist at home, you don't need ...",russian-twist-024,What type of equipment do I need to do a Russi...,PARTLY_RELEVANT,The generated answer provides information that...
69,The lat pulldown mainly targets the back.,lat-pulldown-014,What specific body part does the lat pulldown ...,PARTLY_RELEVANT,The generated answer identifies the general ar...
82,To properly execute a Barbell Hip Thrust exerc...,hip-thrust-032,What equipment do I need to properly execute a...,PARTLY_RELEVANT,The generated answer correctly identifies that...
85,"To perform the Pallof Press exercise, you need...",pallof-press-045,What type of equipment do I need to perform th...,PARTLY_RELEVANT,The generated answer correctly identifies one ...